Release 2020.12.1
okta/okta-developer-docs pull request #1708
Opened 2020-12-15 22:36 UTC by susanharper-okta

## Description:
- **What's changed?** Release 2020.12.1!-- Describe your changes. This will most likely be a copy-paste of your commit message(s), which should be descriptive and informative. -->
- **Is this PR related to a Monolith release?** Release 2020.12.1!-- If so, which one? -->

2020-12-15 22:39 UTC, christinechoy-okta reviewed
Reviewed.

2020-12-15 22:40 UTC, christinechoy-okta approved these changes

2020-12-17 20:29 UTC, jakubvul-okta requested changes

2020-12-17 20:29 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/release-notes/2020-12-1/index.md
> +* The Update User API incorrectly allowed the [credentials object](/docs/reference/api/users/#credentials-object) of an ACTIVE user to be updated to [password hook](/docs/reference/api/users/#passwor
```suggestion
* The Update User API incorrectly allowed the [Credentials object](/docs/reference/api/users/#credentials-object) of an ACTIVE user to be updated to [Password Hook](/docs/reference/api/users/#password-object). (OKTA-350956)
```

2020-12-17 20:35 UTC, jakubvul-okta approved these changes

2020-12-17 21:02 UTC, merged