Warn users about application type mismatch
okta/okta-developer-docs pull request #1723
Opened 2020-12-21 15:44 UTC by oleksandrpravosudko-okta

## Description:
- **What's changed?** 
- Note block quote is added to guides mentioning Okta app creation
- **Is this PR related to a Monolith release?** 
No

### Resolves:

* [OKTA-342950](https://oktainc.atlassian.net/browse/OKTA-342950)

2020-12-21 15:56 UTC, jakubvul-okta requested changes

2020-12-21 15:56 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/setup-app/index.md
> +  > **Note:** It is important to choose appropirate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify app's client secret, whi
```suggestion
  > **Note:** It is important to choose the appropriate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify an app's client secret, which public clients are not designed to have, hence breaking the sign-in or sign-out flow.
```

2020-12-21 15:56 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/implement-implicit/setup-app/index.md
> +  > **Note:** It is important to choose appropirate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify app's client secret, whi
```suggestion
  > **Note:** It is important to choose the appropriate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify an app's client secret, which public clients are not designed to have, hence breaking the sign-in or sign-out flow.
```

2020-12-21 15:56 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md
> +  > **Note:** It is important to choose appropirate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify app's client secret, whi
```suggestion
  > **Note:** It is important to choose the appropriate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify an app's client secret, which public clients are not designed to have, hence breaking the sign-in or sign-out flow.
```

2020-12-21 15:56 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/create-okta-application/index.md
> +  > **Note:** It is important to choose appropirate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify app's client secret, whi
```suggestion
  > **Note:** It is important to choose the appropriate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify an app's client secret, which public clients are not designed to have, hence breaking the sign-in or sign-out flow.
```

2020-12-21 15:56 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
> +> **Note:** It is important to choose appropirate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify app's client secret, which
```suggestion
  > **Note:** It is important to choose the appropriate application type for apps which are public clients. Failing to do so may result in Okta API endpoints attempting to verify an app's client secret, which public clients are not designed to have, hence breaking the sign-in or sign-out flow.
```

2021-01-05 01:30 UTC, aarongranick-okta commented
@oleksandrpravosudko-okta please fix spelling of "appropirate" (yeargh!)

2021-01-08 16:19 UTC, oleksandrpravosudko-okta commented
@aarongranick-okta  there seem to be no more ~seadogs~ "appropirate" occurrances left unfixed

2021-01-08 18:09 UTC, jakubvul-okta approved these changes

2021-01-11 11:01 UTC, merged