Update Developer Documentation to include Event Hook Preview Tab Content
okta/okta-developer-docs pull request #1853
Opened 2021-01-26 19:46 UTC by brianduffield-okta

**What has changed?**

Updates to the following guides:
- [Guides > Hooks > Event Hooks > Test the Event Hook](https://developer.okta.com/docs/guides/event-hook-implementation/nodejs/test-hook/) -- Added content that references the option to preview the hook, as well as test.
- [Guides > Hooks > Common Hook Set Up Steps > Troubleshooting hook implementations](https://developer.okta.com/docs/guides/common-hook-set-up-steps/nodejs/troubleshooting/) -- Added small content mentioning Event Hooks are also preview eligible.
- [Concepts > Event Hooks](https://developer.okta.com/docs/concepts/event-hooks/) -- Added minor conceptual content on preview tab.

**Is this for a monthly release?** Yes. 2020.02.0

**Resolves?** [OKTA-345130 Update event hooks guide to show how to use new preview UI](https://oktainc.atlassian.net/browse/OKTA-345130)

2021-01-26 20:52 UTC, jakubvul-okta requested changes

2021-01-26 20:52 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
> +For a working example of an end-to-end Event Hook setup, see the following guide [Event Hook](/docs/guides/event-hook-implementation).
```suggestion
For a working example of an end-to-end Event Hook setup, see the [Event Hook guide](/docs/guides/event-hook-implementation).
```

2021-01-26 20:52 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/guides/event-hook-implementation/test-hook/index.md
> +To run a preview call of your Event Hook, sign-in to your Okta org as the super admin.
```suggestion
To run a preview call of your Event Hook, sign in to your Okta org as the super admin.
```

2021-01-27 17:44 UTC, quyle-okta commented on packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
> +You can preview the the JSON payload for the Event Hook request from the Admin Console's **Preview** tab, which provides a review of the Event Hook request syntax for the specific Event Type. If veri
@brianduffield-okta The Preview feature actually works for event hooks in both verified and unverified state to reduce friction for developers to test Event Hooks.  I would remove the "If verified," clause.

2021-01-27 17:44 UTC, quyle-okta commented on packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/troubleshooting/index.md
> +A preview tab is also available for Event Hooks, and displays the JSON payload for the selected Event Type. The preview tab can confirm a successful delivery of the request.
@brianduffield-okta Can we hyperlink to the product docs here somehow, ie, link "preview tab" to the https://help.okta.com/en/prod/Content/Topics/automation-hooks/event-hooks-preview.htm URL

2021-01-27 17:44 UTC, quyle-okta commented on packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/troubleshooting/index.md
> +A preview tab, accessible in the Admin Console, is available for the following two Inline Hooks:
@brianduffield-okta Can we link "preview tab" to the Inline Hooks Preview product documentation?
https://help.okta.com/en/prod/Content/Topics/automation-hooks/preview-inline-hooks.htm

2021-01-27 19:07 UTC, quyle-okta approved these changes
Looks good to me!

2021-02-02 22:32 UTC, jakubvul-okta approved these changes

2021-02-02 22:40 UTC, merged