Update index.md
okta/okta-developer-docs pull request #1856
Opened 2021-01-27 15:49 UTC by TheFuzzard

a lot of people that are trying to create an IdP for a workforce scenario are confused by this step as it is not needed for them and the configuration is already complete by this point

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

2021-03-08 17:00 UTC, yuliu-okta approved these changes

2021-03-08 17:18 UTC, IanHakes-okta commented
Text changes haven't been made

2021-03-08 17:29 UTC, IanHakes-okta requested changes
Please update text note according to comment below

2021-03-08 17:34 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
> +> **Note:** If you only need to authenticate users into Okta and not have them redirected to a particular OIDC client the IdP configuration would be complete at this point and [routing rules](https:/
@IanHakes-okta 
If you need Okta only to authenticate users and not to redirect them to a particular OpenID Connect client, then the Identity Provider (IdP) configuration is complete. Add routing rules to redirect users from the Okta Sign-In Page to the IdP.

2021-03-08 17:34 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
> +> **Note:** If you only need to authenticate users into Okta and not have them redirected to a particular OIDC client the IdP configuration would be complete at this point and [routing rules](https:/
@yuliu-okta

2021-03-11 18:52 UTC, susanharper-okta commented
this one can be closed

2021-03-11 18:52 UTC, closed without merging