Review & implement suggestions to Angular sign-in guide
okta/okta-developer-docs pull request #1952
Opened 2021-03-01 13:08 UTC by oleksandrpravosudko-okta

## Description:
- **What's changed?** 
  - vuepress-plugin-code-copy added for 'copy into clipboard' button
  - Angular + SIW guide updated according to suggestions
- **Is this PR related to a Monolith release?** 
No

### Resolves:

* [OKTA-329950](https://oktainc.atlassian.net/browse/OKTA-329950)

2021-03-01 16:02 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
> +You can sign in to Okta Developer Dashboard through [https://login.okta.com](https://login.okta.com) and clicking `Admin` button on Okta Dashboard or by signing in directly into Okta Developer Dashbo
@albertchen-okta confirm please, but I don't think we want to have any instructions for the Developer Console?

2021-03-05 21:32 UTC, susanharper-okta approved these changes
couple knits that I'll commit for you!

2021-03-05 21:32 UTC, susanharper-okta commented on packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
> +* Sign in to the Okta Developer Dashboard, and select **Create New App**. <br/>
```suggestion
* Sign in to the Developer Console, and select **Create New App**. <br/>
```

2021-03-05 21:32 UTC, susanharper-okta commented on packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
> +You can sign in to the Okta Developer Dashboard through [https://login.okta.com](https://login.okta.com) and clicking `Admin` button on the Okta Dashboard.
```suggestion
You can sign in to the Developer Console using [https://login.okta.com](https://login.okta.com), and then click **Admin**.
```

2021-03-05 21:32 UTC, susanharper-okta commented on packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
> +`${clientId}` placeholders further in this tutorial should be replaced by `Client ID` of created application.
```suggestion
`${clientId}` placeholders further in this tutorial should be replaced by the `Client ID` of the created application.
```

2021-03-09 12:08 UTC, oleksandrpravosudko-okta commented
Thank you @susanharper-okta!

@shawyu-okta @francoislehoux-okta  are we good with incorporating `code-copy` plugin?

2021-03-09 14:07 UTC, francoislehoux-okta commented
Nothing against the `code-copy` plugin. I'll +1 @jakubvul comment here, are we sure we want to be referring the `Dev Console` here? It was turned off just last week. Pulling @albertchen-okta in

2021-03-09 22:15 UTC, jakubvul-okta requested changes

2021-03-11 17:43 UTC, francoislehoux-okta approved these changes
Looks good!

2021-03-15 12:55 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
> +You can sign in to the Admin Console using [https://login.okta.com](https://login.okta.com), and then click **Admin**.
```suggestion
You can sign in to the Admin Console using <https://login.okta.com>, and then click **Admin**.
```

2021-03-15 12:55 UTC, jakubvul-okta approved these changes

2021-03-15 16:46 UTC, merged