Release 2021.04.1
okta/okta-developer-docs pull request #2061
Opened 2021-04-14 20:39 UTC by vanngo-okta

## Description:
- **What's changed?** Updating Weekly Release Notes for 2021.04.1
- **Is this PR related to a Monolith release?** Yes - 2021.04.1

### Resolves:

* [OKTA-387034](https://oktainc.atlassian.net/browse/OKTA-387034)

2021-04-14 21:03 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/release-notes/2021/index.md
> +The OAuth authorization code lifetime has increased from one minute to five minutes.<!--OKTA-379556-->
```suggestion
The OAuth 2.0 authorization code lifetime has increased from one minute to five minutes.<!--OKTA-379556-->
```

2021-04-14 21:04 UTC, jakubvul-okta requested changes

2021-04-14 21:04 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/release-notes/2021/index.md
> +The OAuth authorization code lifetime has increased from one minute to five minutes.<!--OKTA-379556-->
```suggestion
The OAuth 2.0 authorization code lifetime has increased from one minute to five minutes. <!--OKTA-379556-->
```

2021-04-14 21:17 UTC, jakubvul-okta approved these changes

2021-04-15 11:28 UTC, brianduffield-okta commented
Preview 2021.04.1 deployed to OP1 April 14 10:21 Eastern; delay forOP2 and OP3 until April 15

2021-04-15 11:28 UTC, merged