Added /login/login.htm endpoint
okta/okta-developer-docs pull request #2073
Opened 2021-04-22 20:46 UTC by christinechoy-okta

## Description:
- **What's changed?** Updated to add /login/login.htm endpoint
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-378466](https://oktainc.atlassian.net/browse/OKTA-378466)

2021-04-23 14:10 UTC, brianduffield-okta requested changes
Found a few things ...

2021-04-23 14:10 UTC, brianduffield-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
>  For client-specific rate limits, three headers show the limit that is being enforced, when it resets, and how close you are to hitting the limit:
Would "For client-specific rates limits, the three headers show the ..." read better?

2021-04-23 14:10 UTC, brianduffield-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
> +**Q: Would the rate limit headers returned by Okta on the `/authorize` or `/login/login.htm` endpoint reflect client-specific rate limits?**
I recall we agreed not to use code format in headings, but we can double-check with team.

2021-04-23 17:16 UTC, christinechoy-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
> +Each valid request made by a user to this endpoint is counted as one request against the respective [authorization server](/docs/concepts/auth-servers/) rate limit bucket - for example, (`/oauth2/{au
I replaced the hyphen with a comma.

2021-04-23 17:32 UTC, christinechoy-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
> +* `X-Rate-Limit-Limit` - The rate limit ceiling that is applicable for the current request to the specific client/IP/device identifier combination (for the `/authorize` endpoint) or the IP/device ide
The style guide says to put periods at the end of bullet points only if they are sentences. Since these are fragments, I left out the period.

2021-04-27 16:41 UTC, haozhao-okta reviewed
two nits, otherwise looks good

2021-04-27 16:41 UTC, haozhao-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
> +Client-based rate limiting for the `/login/login.htm endpoint uses a combination of the user's IP address and Okta device identifier to provide even more granular, more targeted rate limits to a user
`/login/login.htm`

2021-04-27 16:41 UTC, haozhao-okta commented on packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
>  > **Note:** If a client-based rate limit is in **Log per client** or **No action** mode, headers that are returned still reflect the org-wide rate limits.
@ZoeMonosson-okta , since we use `Do nothing` in the UI, shall we replace `No action` to `Do nothing` as well?

2021-04-27 19:04 UTC, brianduffield-okta approved these changes

2021-04-27 19:23 UTC, merged