update conductor.yml redirect url
okta/okta-developer-docs pull request #2076
Opened 2021-04-23 12:43 UTC by volodymyrmakarchuk-okta

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-377156](https://oktainc.atlassian.net/browse/OKTA-377156)

2021-04-23 16:02 UTC, jakubvul-okta approved these changes

2021-04-26 11:07 UTC, volodymyrmakarchuk-okta commented
@shawyu-okta  after I've tested redirecting on stage I found that it redirecting to this page. Is that fine?

<img width="1159" alt="Screenshot at Apr 26 14-06-52" src="https://user-images.githubusercontent.com/71866734/116073176-bc572680-a698-11eb-87b8-d5124dcfa6f0.png">

2021-04-26 14:39 UTC, shawyu-okta requested changes
`/integrate-with-okta` should redirect to the page with `https://developer.okta.com/okta-integration-network/`

2021-04-26 15:45 UTC, volodymyrmakarchuk-okta commented on packages/@okta/vuepress-site/conductor.yml
> +  - from: /integrate-with-okta
do I need to update some others files except  .yaml file? I'm trying to navigate to `/okta-integration-network` but it also doesn't work and showing like the page that not found

2021-05-14 07:43 UTC, volodymyrmakarchuk-okta commented on packages/@okta/vuepress-site/conductor.yml
> +  - from: /integrate-with-okta
@brianduffield-okta I've added this code to `conductor.yml` but it still didn't help, any ideas about what I did wrong?

2021-05-20 18:03 UTC, brianduffield-okta commented on packages/@okta/vuepress-site/conductor.yml
> +  - from: /integrate-with-okta
@volodymyrmakarchuk-okta   Sorry, must've missed this earlier.  Can you confirm what redirect you want to use? The code I mentioned in my previous comment is already working on the live site, e.g., https://developer.okta.com/integrate-with-okta goes to https://developer.okta.com/okta-integration-network/

(I might've made that change myself when I recently added some redirects for Hook guides).

2021-05-21 06:40 UTC, volodymyrmakarchuk-okta commented on packages/@okta/vuepress-site/conductor.yml
> +  - from: /integrate-with-okta
oh, that's right, I'm wanna add urls that you mentioned, 
@brianduffield-okta  thanks for resolving this task =) Gonna close task.
But still wondering why I couldn't test that on stage.

2021-05-21 06:54 UTC, closed without merging