Update IDP Discovery Policy with Multi IDP support
okta/okta-developer-docs pull request #2102
Opened 2021-05-03 17:53 UTC by romantkachuk-okta

## Description:
- Add Multi IdP support description brought together with OIE

### Resolves:

* [OKTA-385366](https://oktainc.atlassian.net/browse/OKTA-385366)

2021-05-03 20:20 UTC, jakubvul-okta requested changes

2021-05-03 21:48 UTC, romantkachuk-okta commented on packages/@okta/vuepress-site/docs/reference/api/policy/index.md
> +* Single rule can contain with up to 10 providers
I've rephrased it a little bit. Meant Policy Action

2021-05-03 21:49 UTC, romantkachuk-okta commented
@jakubvul-okta please review updates, thanks!

2021-05-03 22:08 UTC, jakubvul-okta approved these changes

2021-05-04 15:18 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/reference/api/policy/index.md
> +| type                               | Provider type           | `OKTA`, `AgentlessDSSO`, `IWA`, `X509`, `SAML2`, `OIDC`, `APPLE`, `FACEBOOK`, `GOOGLE`, `LINKEDIN`, `MICROSOFT` | Yes |
```suggestion
| type                               | Provider type. Possible values: `OKTA`, `AgentlessDSSO`, `IWA`, `X509`, `SAML2`, `OIDC`, `APPLE`, `FACEBOOK`, `GOOGLE`, `LINKEDIN`, `MICROSOFT`  | String | Yes |
```

2021-05-04 15:22 UTC, jakubvul-okta approved these changes

2021-05-04 16:53 UTC, jameszhang-okta approved these changes

2021-05-04 17:04 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/reference/api/policy/index.md
> +Multiple IdP instances can be defined in a single Policy Action. It allows User to choose a Provider to sign in with.
```suggestion
Multiple IdP instances can be defined in a single Policy Action. This allows users to choose a Provider when they sign in.
```

2021-05-04 17:04 UTC, jakubvul-okta commented on packages/@okta/vuepress-site/docs/reference/api/policy/index.md
> +| type                               | Provider type           | `OKTA`, `AgentlessDSSO`, `IWA`, `X509`, `SAML2`, `OIDC`, `APPLE`, `FACEBOOK`, `GOOGLE`, `LINKEDIN`, `MICROSOFT` | Yes |
```suggestion
| type                               | Provider type. Possible values: `OKTA`, `AgentlessDSSO`, `IWA`, `X509`, `SAML2`, `OIDC`, `APPLE`, `FACEBOOK`, `GOOGLE`, `LINKEDIN`, `MICROSOFT`           | String | Yes |
```

2021-05-04 17:04 UTC, jakubvul-okta approved these changes

2021-05-04 17:05 UTC, merged