Removed game banner from frontpage and banner css
okta/okta-developer-docs pull request #2314
Opened 2021-07-12 19:17 UTC by AndriiDovhopolov-okta

## Description:
- Removed banner and css
- 
### Resolves:
* [OKTA-408552](https://oktainc.atlassian.net/browse/OKTA-408552)

2021-07-13 15:49 UTC, albertchen-okta requested changes

2021-07-13 15:49 UTC, albertchen-okta commented on packages/@okta/vuepress-theme-prose/components/Home.vue
> +                  Check out the event website for agenda, speakers + breakout
This should be regular font (not bold)

I propose the text should be "Learn how to add security to your apps, APIs, and infrastructure. Register for free!"

2021-07-13 18:16 UTC, alexdahl-okta requested changes
I'm going to follow up with some internal stakeholders; please hold.

2021-07-16 16:14 UTC, albertchen-okta commented
Closing this out. Sorry Andrii, you did this exactly as asked, but between PM/design, we decided to hold off to re-implement this as a native banner. Alex Cohen (Brand Design) is working on the new banner, and we will open a new PR to implement it.

2021-07-16 16:14 UTC, closed without merging