Update Dynamic Client Registration API reference
okta/okta-developer-docs pull request #2425
Opened 2021-08-10 16:34 UTC by brianduffield-okta

## Description:
- **What's changed?** "Fixed the JSON request in the "Register new client" POST example. Removed "refresh_token" from grant types because the current JSON request doesn't work." <br>
Re-created this PR from https://github.com/okta/okta-developer-docs/pull/2350 Thanks for original PR, @patrickjburke245 <br>
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* n/a

2021-08-10 18:01 UTC, larsjohansen-okta requested changes

2021-08-10 18:01 UTC, larsjohansen-okta commented on packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
> -     "refresh_token"
We should not remove this, we should instead add `implicit` to the list of grant types.

2021-08-11 04:15 UTC, huanliu-okta commented
@brianduffield-okta have you tested this to be working?

2021-08-11 18:20 UTC, brianduffield-okta commented
@huanliu-okta I did a simple test with the Postman collection (which includes `implicit` in the Create Client API call), and it works. Removing `implicit` also returned an error. @larsjohansen-okta may have done other testing. Is this enough to update docs?

2021-08-11 21:13 UTC, huanliu-okta approved these changes
Just want to make sure we tested the change. LGTM.

2021-08-12 17:38 UTC, larsjohansen-okta approved these changes

2021-08-12 19:27 UTC, merged