remove docs page
okta/okta-developer-docs pull request #2439
Opened 2021-08-13 09:22 UTC by volodymyrmakarchuk-okta

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-363923](https://oktainc.atlassian.net/browse/OKTA-363923)

2021-08-13 13:27 UTC, robertnicolo-okta requested changes
When attempting to test this change locally, a redirect did not occur and instead 304s were returned. I tried in Chrome private mode and also in safari which I never used. It seems the 304 is a server cache response. See images below:

**Page I saw**
![image](https://user-images.githubusercontent.com/78044107/129363924-6ed94535-0199-4313-ae8b-05ae73edff84.png)


**304 Server Response:**
![image](https://user-images.githubusercontent.com/78044107/129363866-b045c67a-0567-4e1a-8ac5-018355e6cc44.png)

I think maybe the server cache needs to be flushed of the page. Would this happen in production and is there are any other changes that need to be made?

2021-08-13 17:36 UTC, volodymyrmakarchuk-okta commented
@robertnicolo-okta Redirection is not working locally, please check trex configuration instead
https://vuepress-site.trexcloud.com/

2021-08-14 20:16 UTC, robertnicolo-okta requested changes
Hi,

I retested using the "https://vuepress-site.trexcloud.com/" site and noticed two redirect bounces before ending up at the homepage.  See screenshot:

![image](https://user-images.githubusercontent.com/78044107/129458999-56041151-5ef5-42dc-a519-5999e7b8d926.png)

2021-08-15 08:30 UTC, volodymyrmakarchuk-okta commented
@robertnicolo-okta seems this behavior is a common pattern for SEO optimization, 301 redirections on trailing slash version prevent content duplication, here I found reasonable article https://www.onlineassetpartners.co.nz/blog/how-trailing-slashes-affect-your-websites-seo/

Also, you may want to check conductor.yml file. This file contains settings for route redirects, and we use one approach for all redirects so redirect behavior with 301 code seems applicable for all routes

2021-08-16 13:52 UTC, shawyu-okta approved these changes

2021-08-16 13:52 UTC, shawyu-okta commented on packages/@okta/vuepress-site/docs/index.md
> -component: Documentation
See if the vue component can be deleted, too. It's probably the only page that uses it

2021-08-16 16:51 UTC, shawyu-okta approved these changes

2021-08-18 00:36 UTC, robertnicolo-okta approved these changes
lgtm

2021-08-18 09:17 UTC, merged