fixing broken links
okta/okta-developer-docs pull request #2726
Opened 2021-11-04 13:34 UTC by chrisdmills-okta

## Description:
- **What's changed?** Fixing some broken links that have appeared since some of the multi-page to single page work.
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-443780](https://oktainc.atlassian.net/browse/OKTA-443780)

2021-11-05 13:50 UTC, vanngo-okta requested changes
A few nits.

2021-11-05 13:50 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/index.md
> +* Biometric unlock with Touch ID, Face ID, and Smart Lock — added by following the [Sign users in to your mobile apps](/docs/guides/sign-into-mobile-app/android/main/) guide.
```suggestion
* Biometric unlock with Touch ID, Face ID, and Smart Lock — added by following the [Sign users in to your mobile apps](/docs/guides/sign-into-mobile-app/) guide.
```

2021-11-05 13:50 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/index.md
> +When you [configure the Okta SDK](/docs/guides/sign-into-mobile-app/android/main/#add-and-configure-packages) with the `offline_access` scope, your mobile app gets a refresh token from Okta. The refr
```suggestion
When you [configure the Okta SDK](/docs/guides/sign-into-mobile-app/-/main/#add-and-configure-packages) with the `offline_access` scope, your mobile app gets a refresh token from Okta. The refresh token is long-lived and is used to keep the user signed in to your app.
```
Both this page and the /sign-into-mobile-app/ page contain the same stack selectors, so we can't hardcode "android".

2021-11-05 13:50 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/create-an-okta-application/index.md
> +Use the Okta application that you created when you walked through the [Sign users in to your mobile app](/docs/guides/sign-into-mobile-app/main/) guide.
```suggestion
Use the Okta application that you created when you walked through the [Sign users in to your mobile app](/docs/guides/sign-into-mobile-app/) guide.
```
Removing "/main/" is cleaner. Plus, it avoids the broken nav and bread-crumbs bug.

2021-11-05 13:50 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/configure-packages/index.md
> +You should already have added and configured packages when you walked through the [Sign users in to your mobile app](/docs/guides/sign-into-mobile-app/android/main/) guide.
```suggestion
You should already have added and configured packages when you walked through the [Sign users in to your mobile app](/docs/guides/sign-into-mobile-app/-/main/#add-and-configure-packages) guide.
```

This breaks the left-nav and breadcrumbs, but at least it's jumping to the right section with the selected language preserved.

2021-11-08 15:36 UTC, chrisdmills-okta commented
@vanngo-okta suggestions all committed. Thanks!

2021-11-08 16:34 UTC, vanngo-okta approved these changes
LGTM! 🚀

2021-11-08 17:27 UTC, merged