Napa docs3 add sdk to your app go
okta/okta-developer-docs pull request #2804
Opened 2021-11-17 19:22 UTC by robertnicolo-okta

## Description:
1. Added the Go language to the **Add the Identity Engine SDK to your app** document
2. Minor updates to the Swift **Add the Identity Engine SDK to your app** document
3. Main the **Next Steps** section language specific to accommodate Go's lack of a **Upgrade your application to the Okta Identity Engine SDK** Document. In the process, fixed missing links to the **Upgrade ..** doc in some languages.

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

2021-11-18 02:22 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/go/addsdk.md
> +1. Add the SDK to your go.mod file: `go get github.com/okta/okta-idx-golang`
```suggestion
1. Add the SDK to your `go.mod` file: `go get github.com/okta/okta-idx-golang`
```

2021-11-18 02:23 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/go/addsdk.md
> +1. Import the package in your project: `import "github.com/okta/okta-idx-golang"`
```suggestion
1. Import the package into your project: `import "github.com/okta/okta-idx-golang"`
```

2021-11-18 02:25 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/go/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to [get set up](/docs/guides/oie-embedded-common-org-setup/go/main/) with your Okta org. Also, check out the [sample apps](/docs/gu
Might be redundant. I think that saying "after you've added" implies completion.
```suggestion
After you add the SDK to your app, the next step is to get [set up](/docs/guides/oie-embedded-common-org-setup/go/main/) with your Okta org. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:27 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/android/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK]
```suggestion
After adding the SDK to your app, upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK](/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/android/main/) to learn how to map your existing implementations to the Identity Engine SDK. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:28 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/aspnet/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK]
```suggestion
After adding the SDK to your app, upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK](/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/aspnet/main/) to learn how to map your existing implementations to the Identity Engine SDK. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:28 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/go/addsdk.md
> +After you upgrade your app to the minimum requirements, the next step is to add the Identity Engine SDK to your app.
```suggestion
After you upgrade your app to the minimum requirements, add the Identity Engine SDK to your app.
```

2021-11-18 02:28 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK]
```suggestion
After adding the SDK to your app, upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK](/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/ios/main/) to learn how to map your existing implementations to the Identity Engine SDK. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:29 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/java/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK]
```suggestion
After adding the SDK to your app, upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK](/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/java/main/) to learn how to map your existing implementations to the Identity Engine SDK. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:29 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/nodejs/langspecificmapguide.md
> +After you’ve completed adding the SDK to your app, the next step is to upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK]
```suggestion
After adding the SDK to your app, upgrade your authentication use cases to the Identity Engine SDK. See [Upgrade your application to the Okta Identity Engine SDK](/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/nodejs/main/) to learn how to map your existing implementations to the Identity Engine SDK. Also, check out the [sample apps](/docs/guides/oie-embedded-common-run-samples) to see working examples of all the supported use cases using the Identity Engine SDK.
```

2021-11-18 02:30 UTC, brentschaus-okta requested changes
Just a few suggestions. Let me know what you think!

2021-11-18 17:59 UTC, robertnicolo-okta commented
Thanks, @brentschaus-okta. I committed all of your suggestions.

2021-11-19 21:08 UTC, brentschaus-okta approved these changes
🚢

2021-11-29 18:59 UTC, merged