update vue quickstart instructions
okta/okta-developer-docs pull request #2828
Opened 2021-11-19 16:28 UTC by alisaduncan

## Description:
- **What's changed?** Update the Vue quickstart guide to use Vue 3, updated sdk usages, and better match code samples so devs have a better experience getting going.
- **Is this PR related to a Monolith release?** No, I don't think so

### Resolves:

* No Jira ticket yet

2021-12-02 08:08 UTC, chrisdmills-okta commented
@shuowu-okta another one that we'd love your help on, if you have the time.

2021-12-02 23:51 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/reqauthspecific.md
> +Set the `requiresAuth` property to `true` in the optional `meta` object as part of the route definition. Add `navigationGuard` function from `okta-vue` as a global guard to the router.
```suggestion
Set the `requiresAuth` property to `true` in the optional `meta` object as part of the route definition. Add the `navigationGuard` function from `okta-vue` as a global guard to the router.
```

2021-12-03 17:09 UTC, shuowu-okta approved these changes

2021-12-03 17:26 UTC, chrisdmills-okta requested changes
@alisaduncan just a couple of small stylistic comments for you to address here.

2021-12-03 17:26 UTC, chrisdmills-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/reqauthspecific.md
> +Set the `requiresAuth` property to `true` in the optional `meta` object as part of the route definition. Add `navigationGuard` function from `okta-vue` as a global guard to the router.
I think the wording could be clearer here. Would "Add the `navigationGuard` function from `okta-vue` to the router as a global guard." still make sense?

2021-12-03 17:26 UTC, chrisdmills-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/config.md
> +First, create an [OktaAuth](https://github.com/okta/okta-auth-js) object with your configuration and pass it to the `okta-vue` plugin. You need to use `okta-vue` plugin after adding the router to the
"to use `okta-vue` plugin" -> "to use the `okta-vue` plugin"?

2021-12-03 20:09 UTC, alisaduncan commented
@chrisdmills-okta I addressed both comments and rebased to latest

2021-12-03 22:16 UTC, chrisdmills-okta approved these changes
Perfect, thanks @alisaduncan ! Let's put this one to bed.

2021-12-03 22:17 UTC, merged