OKTA-438749 multi to single custom widget
okta/okta-developer-docs pull request #2854
Opened 2021-12-03 03:00 UTC by brentschaus-okta

## Description:
- **What's changed?** Converting the "style yer widget" pages from many to one.
- **Is this PR related to a Monolith release?** Nein.

### Resolves:

* [OKTA-438749](https://oktainc.atlassian.net/browse/OKTA-438749)

2021-12-03 23:36 UTC, vanngo-okta requested changes
What you have in the conductor.yml file looks good, but there are a few links **to** `*/style-the-widget/*` (line 2083 - 2089) that needs to be updated. A few nits on the headings, but other than that, the rest looks good!

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/index.md
> +* [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```suggestion
* [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/main/index.md
> +To learn how to customize the sign-in page, see [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```suggestion
To learn how to customize the sign-in page, see [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/main/index.md
> +* In this guide you signed users in to your app by opening a browser. To learn how to customize the sign-in page displayed in the browser, see [Style the Widget](/docs/guides/custom-widget/main/#styl
```suggestion
* In this guide you signed users in to your app by opening a browser. To learn how to customize the sign-in page displayed in the browser, see [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/index.md
> +> **Note:** To customize this sign-in page, see the [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```suggestion
> **Note:** To customize this sign-in page, see the [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/index.md
> +* [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```suggestion
* [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/index.md
> +> **Note:** To customize the hosted sign-in page, see [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```suggestion
> **Note:** To customize the hosted sign-in page, see [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget).
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/index.md
> +* [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```suggestion
* [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md
> +* [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```suggestion
* [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget)
```

2021-12-03 23:36 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/authn/index.md
> +> **Note:** The WebAuthN Factor is available for those using the [Style the Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget). If you are using a self-hosted, customized
```suggestion
> **Note:** The WebAuthN Factor is available for those using the [Style the Okta-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget). If you are using a self-hosted, customized sign-in widget, you must first upgrade to widget version 3.4.0 and enable the [configuration option](https://github.com/okta/okta-signin-widget#configuration).
```

2021-12-03 23:36 UTC, brentschaus-okta commented
Test comment from mobile app.

2021-12-03 23:53 UTC, brentschaus-okta commented
> What you have in the conductor.yml file looks good, but there are a few links **to** `*/style-the-widget/*` (line 2083 - 2089) that needs to be updated. A few nits on the headings, but other than that, the rest looks good!

Great catch. Thanks!

2021-12-04 00:23 UTC, vanngo-okta approved these changes
Sorry, I missed one last anchor. 
The rest LGTM! 🚀

2021-12-04 00:23 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-styling/main/index.md
> +After you upgrade your Sign-In Widget to Okta Identity Engine, you can modify the look of the initial sign-in page. See [Style the self-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-t
```suggestion
After you upgrade your Sign-In Widget to Okta Identity Engine, you can modify the look of the initial sign-in page. See [Style the self-hosted Sign-In Widget](/docs/guides/custom-widget/main/#style-the-self-hosted-sign-in-widget) for examples and information on how to [modify the initial sign-in page](/docs/guides/custom-widget/main/#initial-sign-in-page) and how to make your own customizations to the Widget such as [increasing the Widget's width](/docs/guides/custom-widget/main/#widget-positioning-width) and [adding a background color](/docs/guides/custom-widget/main/#background).
```

2021-12-04 01:05 UTC, merged