Update stack-selector styles/behaviour
okta/okta-developer-docs pull request #2876
Opened 2021-12-08 13:26 UTC by aanton-g

## Description:
- Update stack-selector styles/behaviour
- Adding a Stack selector menu to the side menu

### Resolves:

* [Fixing stack selector and putting the changes live](https://trello.com/c/Yoi8h24u/1-1-fixing-stack-selector-and-putting-the-changes-live)

2021-12-13 20:29 UTC, robertnicolo-okta requested changes
# Stack selector review
**Git PR:** [https://github.com/okta/okta-developer-docs/pull/2876](https://github.com/okta/okta-developer-docs/pull/2876)
**Jira Epic:** [https://oktainc.atlassian.net/browse/OKTA-436568](https://oktainc.atlassian.net/browse/OKTA-436568)
**Trello board:** [https://trello.com/c/Yoi8h24u/1-1-fixing-stack-selector-and-putting-the-changes-live)](https://trello.com/c/Yoi8h24u/1-1-fixing-stack-selector-and-putting-the-changes-live)

## Pre-review comments
Some of my review criteria were based on fixing the issues tied to the Stack selector bugs and enhancements [epic](https://oktainc.atlassian.net/browse/OKTA-436568). Great first draft of the stack selector functionality BTW. Things really look polished.  

## Review comments

- “No code snippet defined” in some guides. See video for more details: https://drive.google.com/file/d/1SPgY5ZTmcGXDuS_Un7wWgJvxjkVBfaGg/view?usp=sharing
- Javascript errors on pages: See video for more details: https://drive.google.com/file/d/1FrrCwU5-1jrf3bE0BM7swPpSzuvPEszA/view?usp=sharing
- Dead space between items. See video for more details: https://drive.google.com/file/d/1EnlGIFUS6Xv5mSxoLAOsvYO51PN5X4Mk/view?usp=sharing
- Left navbar not keeping selection for generic guide references. See video for more details: https://drive.google.com/file/d/1C3jakgck7n82ydE73OSC6L_OtUxNsGdw/view?usp=sharing
- Missing H3 headers. See video for more details: https://drive.google.com/file/d/15mZvcHELD-2Q2PNi_nTZrwwXg_h8-5Ej/view?usp=sharing

2021-12-14 09:22 UTC, chrisdmills-okta commented
Thanks for the review @robertnicolo-okta . Note that the Ramotion staff don't have access to the internal Okta systems. @aanton-g let me know if you can't access these videos. I think you should be able to with any Box account, but if not, let us know, and we'll put them somewhere else.

2021-12-14 19:07 UTC, chrisdmills-okta commented
@shawyu-okta @francoislehoux-okta tagging you for visibility.

2021-12-15 22:12 UTC, vanngo-okta reviewed
The StackSelector on the right looks good! A few comments:
1. The "No code snippet defined" (that Robert mentioned above) may not be a problem because we have converted all of the docs away from the multi-page guides. In the old multi-page guides, the file structure was different: the subfolders did not contain snippet files.
2. In the StackSelector drop-down menu item, the mouse-on box seems to not cover the menu item completely (there is a small padding above the mouse-on box). I think this is similar to what Robert described as "dead space between items"?
3. H2 and H3 headers in the snippet files are not showing up in the "On This Page" right-nav (outstanding issue OKTA-446179). - Btw, can we change that title to "On this page" ?
4. Generic links to StackSelector guides are still not working (outstanding issue OKTA-440747). For example, If you are on this page: https://developer.okta.com/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/nodejs/main/, and you click on the link to https://developer.okta.com/docs/guides/oie-embedded-common-org-setup/-/main/#set-up-your-okta-org-for-a-password-factor-only-use-case, then you would expect to go to the "Get set up" page with "Node.js" StackSelector selected. The link directs you to the proper anchor, but the StackSelector not selected, defaulting to "Android", the left-nav does not open to the file location on the menu, and the breadcrumbs at the top are missing. 

Also, please note that we are not using the `<StackSelector snippet="snippetfile" noSelector />` element anymore, we are using the `<StackSnippet snippet="snippetfile" />` element. But this should not affect you?

Thanks for this work!

2021-12-16 08:47 UTC, chrisdmills-okta commented
Thanks for the review @vanngo-okta , this is really helpful.

@aanton-g , since you can't access our JIRA system, I've put the content of the JIRA ticket Van references into our [Stack selector bugs and enhancements GDoc](https://docs.google.com/document/d/12IrCuQb2q3M1Z6Ye-KgvM2-hwgI4JCBke3H5rDvgvyo/edit#heading=h.4kgqrl5d8i9o), at the bottom.

2021-12-20 16:05 UTC, shawyu-okta commented on packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
> +      @include media("<=1439px") {
Can we use a predefined named size instead of an explicit number here? See below where we use "desktop"

2021-12-20 16:06 UTC, shawyu-okta commented on packages/@okta/vuepress-theme-prose/assets/css/components/_stackSelector.scss
> +      @include media(">1439px") {
same comment here about using a named media selector if possible

2022-01-21 11:59 UTC, ulyanash commented
> 

@aanton-g Anton has made his last task changes on December 23 fixing Stack Selector related comments. Please review the changes.
Then the PR comments #3 and #4 from @vanngo-okta will take time and are out of scope for this task. I hope there will be separate tasks for them in trello.

2022-01-21 12:29 UTC, chrisdmills-okta commented
@robertnicolo-okta @vanngo-okta I just found out that some updates were made to this, the stack selector update PR. When you get a chance, can you review the updates to see if your concerns have been addressed? Thanks!

2022-01-26 19:37 UTC, robertnicolo-okta commented
## Stack selector review (2022-01-26)

My review comments are based on the changes I pulled down on 2022-01-26 from the **aanton-g:stack-selector-fix** forked branch.

### Review comments

1. Per @vanngo-okta initial feedback, I'm still noticing "noSelector" still being used. This attribute is deprecated and should be removed.
2. Stack selector is not aligned with **Instructors for** label:

![image](https://user-images.githubusercontent.com/78044107/151233834-bbe4b0c5-7982-4be3-a38f-bb6fe7a7f8e9.png)

3.  The first three items in my initial review have been resolved.
4. I skipped testing the two remaining issues since they will be resolved in other PRs. These other two issues are:
    a. **navbar not keeping selection for generic guide references**. See video for more details: https://drive.google.com/file/d/1C3jakgck7n82ydE73OSC6L_OtUxNsGdw/view?usp=sharing
   b. **Missing H3 headers.** See video for more details: https://drive.google.com/file/d/15mZvcHELD-2Q2PNi_nTZrwwXg_h8-5Ej/view?usp=sharing
6. Can we update this branch with the latest on the master branch? There has been a lot of work centered around single-page guides and I would like to see how the stack selector integrates with those redesigned guides.

### Non review comments

1. @chrisdmills-okta:The black border around the stack selector is somewhat harsh compared to other elements on the page. Should we get Alex Cohen to review the styling?  

![image](https://user-images.githubusercontent.com/78044107/151232977-47936ff5-3cb8-4fa4-a1ec-fe0d5c0cb3d4.png)

2022-02-04 09:54 UTC, merged