Changed StackSelector to StackSnippet
okta/okta-developer-docs pull request #2892
Opened 2021-12-10 22:50 UTC by timhowie-okta

## Description:
- **What's changed?** Changed instances of StackSelector to StackSnippet
- **Is this PR related to a Monolith release?** 

### Resolves:

* This is not part of an existing JIRA, but was triggered by @susanharper-okta review of OKTA-451114/451115/451116 and the switches of those from StackSelector to StackSnippet

2021-12-16 19:07 UTC, vanngo-okta requested changes
The updates in the files in this PR looks good.
Do you have plans to update the `/docs/guides/social-login/main/index.md` and  `/docs/guides/social-login/main/github/noemail.md` files?

- Also, there is an extra space in `/docs/guides/add-an-external-idp/main/apple/appatidp.md` that is not rendering the snippet properly, line 5: `< StackSnippet snippet="idp" inline />`
- Similarly in `/docs/guides/add-an-external-idp/main/apple/appidpinokta.md`, line 6:  `< StackSnippet snippet="idp" inline />`

2021-12-16 21:26 UTC, vanngo-okta commented
> 
Nevermind about the space in the `< StackSnippet>` bug, I'll fix it in another PR.

2021-12-17 20:12 UTC, vanngo-okta reviewed
Hi Tim, I talked to Susan about the snippet structure and we suggest removing generalized snippets within the framework folder. There will be some StackSelector code changes coming soon and reducing unnecessary snippet calls might avoid future problems. Let me know if you want to discuss any of the suggestions. Thanks!

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/paypal/create-app.md
> +[Create an app](https://developer.paypal.com/docs/api-basics/manage-apps/#create-or-edit-sandbox-and-live-apps) and [configure it](https://developer.paypal.com/docs/log-in-with-paypal/integrate/#enab
Can we remove create-app.md and put the specific Paypal info into apptype.md and follow the other IdP section with: 
`Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.`

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/paypal/idpaccount.md
> +[<StackSnippet snippet="idp" inline />](https://www.paypal.com/signin). You can also test using a PayPal sandbox. See [<StackSnippet snippet="idp" inline /> sandbox testing guide](https://developer.p
```suggestion
[PayPal](https://www.paypal.com/signin). You can also test using a PayPal sandbox. See [PayPal sandbox testing guide](https://developer.paypal.com/docs/api-basics/sandbox/)
```

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/salesforce/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
Remove create-app.md and move content to /main/index.md

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/salesforce/idpaccount.md
> +[<StackSnippet snippet="idp" inline />](https://login.salesforce.com/)
```suggestion
[Salesforce](https://login.salesforce.com/)
```

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
Remove create-app.md and use content that should already be in /main/index.md.

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/idpaccount.md
> +[<StackSnippet snippet="idp" inline />](https://login.yahoo.com/)
```suggestion
[Yahoo](https://login.yahoo.com/)
```

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoojp/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
Remove create-app.md and use content in /main/index.md.

2021-12-17 20:12 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoojp/idpaccount.md
> +[<StackSnippet snippet="idp" inline />](https://login.yahoo.co.jp/config/login)
```suggestion
[Yahoo Japan](https://login.yahoo.co.jp/config/login)
```

2022-01-14 17:11 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/github/idpaccount.md
> +[<StackSnippet snippet="idp" inline />](https://github.com/join)
This was implemented. Issue resolved.

2022-01-14 17:16 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/amazon/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:16 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/github/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/gitlab/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/paypal/create-app.md
> +[Create an app](https://developer.paypal.com/docs/api-basics/manage-apps/#create-or-edit-sandbox-and-live-apps) and [configure it](https://developer.paypal.com/docs/log-in-with-paypal/integrate/#enab
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/salesforce/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/yahoojp/create-app.md
> +Create and register <StackSnippet snippet="apptype" inline /> at <StackSnippet snippet="idp" inline />.
This will be addressed in another PR for OKTA-459709.

2022-01-14 17:58 UTC, vanngo-okta approved these changes

2022-01-14 19:14 UTC, susanharper-okta approved these changes
while the likelihood of a product name changing is extremely remote - I pity the person that has to now do a search and replace within all of those files to change the product name, should that happen!!

LGTM!

2022-01-14 20:46 UTC, merged