Fix assorted typos/small errors in Administrator Roles docs
okta/okta-developer-docs pull request #2950
Opened 2022-01-11 22:17 UTC by bobhogg-okta

## Description:
- **What's changed?**

Fixes assorted typos and mistakes in Administrator Roles API docs.

- **Is this PR related to a Monolith release?** **No**

### Resolves:

* [OKTA-459727](https://oktainc.atlassian.net/browse/OKTA-459727)

2022-01-12 14:50 UTC, williamngo-okta approved these changes

2022-01-12 18:06 UTC, rickyyang-okta approved these changes

2022-01-13 15:28 UTC, brentschaus-okta requested changes
Hi @bobhogg-okta , when I run a yarn build for this branch, I see we missed a few:
- The description under "Deletes a Custom Role": /docs/reference/api/roles/#delete-role
- The heading for "Custom Role properties": /docs/reference/api/roles/#custom-role-properties

2022-01-13 15:37 UTC, bobhogg-okta commented
Whoops, you're right. Thanks @brentschaus-okta . Corrected.

2022-01-13 15:53 UTC, brentschaus-okta approved these changes
LGTM!

I'll wait for the checks to complete, then I'll merge.

2022-01-13 15:53 UTC, merged