OKTA-473379 Add LINE social IdP guide
okta/okta-developer-docs pull request #3125
Opened 2022-03-08 17:22 UTC by vanngo-okta

## Description:
- **What's changed?** Add LINE social IdP guide to the "Add an Identity Provider" section.
- **Is this PR related to a Monolith release?** No
### Resolves:

* [OKTA-473379](https://oktainc.atlassian.net/browse/OKTA-473379)

2022-03-08 17:57 UTC, johnbaldo-okta approved these changes

2022-03-08 19:39 UTC, colekurashige-okta reviewed
One comment about emails, LGTM otherwise.

2022-03-08 19:39 UTC, colekurashige-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +
Can we add a blurb about what to do if you can't see a user's email address?

It's my understanding that LINE requires you to do something in order to collect email addresses. See here: https://developers.line.biz/en/docs/line-login/integrate-line-login/#applying-for-email-permission. So my thought is to have something like


> ###

```suggestion
### The user has an email address in LINE, but it's not showing up in Okta
Before you proceed to the next section, test your integration with a user who has an email in LINE. If you don't see their email in Okta, check that you have [email address permission](https://developers.line.biz/en/docs/line-login/integrate-line-login/#applying-for-email-permission) in the channel you are using. If you have confirmed that you have this permission and are still not able to see their emails in Okta, contact support.

### The user doesn't have an email address in LINE
```

2022-03-08 22:27 UTC, colekurashige-okta approved these changes

2022-03-09 14:47 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +Before you proceed to the next section, test your integration with a user who has an email in LINE. If you don't see their email in Okta, verify that you have [email address permission](https://devel
The link text reads awkward to me. I know it's the content in the URL, but I wonder what "email address permission" is. The header content in the Link docs is more clear, imo.
```suggestion
Before you proceed to the next section, test your integration with a user who has an email in LINE. If you don't see their email in Okta, verify that you have permission to [access the user's email address](https://developers.line.biz/en/docs/line-login/integrate-line-login/#applying-for-email-permission) in your LINE channel. If you've confirmed that your channel has email permission and you're still unable to see user emails in Okta, [contact support](https://support.okta.com/help/s/opencase).
```

2022-03-09 14:55 UTC, brentschaus-okta approved these changes
LGTMBBQ!

Just one suggested edit. A minor one.

2022-03-09 21:41 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +To generate user login values and email addresses for LINE users, do the following:
```suggestion
To generate user sign-in values and email addresses for LINE users, do the following:
```

2022-03-09 21:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +1. Locate LINE in the list of providers, then click **Configure** > **Edit Profile and Mappings**.
```suggestion
1. Locate LINE in the list of providers, and then click **Configure** > **Edit Profile and Mappings**.
```

2022-03-09 21:42 UTC, susanharper-okta approved these changes
one tiny nit. LGTM 🚢

2022-04-13 21:22 UTC, colekurashige-okta requested changes
I was careless and didn't check that we were using the correct `id`.

2022-04-13 21:22 UTC, colekurashige-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +   appuser.email == null ? appuser.id + '@line.example.com' : appuser.email
This needs to be `appuser.sub`.

2022-04-13 21:22 UTC, colekurashige-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +   appuser.email == null ? appuser.id + '@line.example.com' : appuser.email
This needs to be `appuser.sub`.

2022-04-13 21:22 UTC, colekurashige-okta commented on packages/@okta/vuepress-site/docs/guides/social-login/main/line/noemail.md
> +   idpuser.email == null ? idpuser.id + '@line.example.com' : idpuser.email
This needs to be `idpuser.sub`.

2022-06-17 17:21 UTC, colekurashige-okta approved these changes
👍 LGTM, we can merge once LINE is published.

2023-01-25 23:12 UTC, closed without merging