WebAuthn authenticator guide For Java
okta/okta-developer-docs pull request #3286
Opened 2022-04-26 03:04 UTC by robertnicolo-okta

## Description:
WebAuthn authenticator guide For Java

### Resolves:

* [OKTA-459404](https://oktainc.atlassian.net/browse/OKTA-459404)

2022-04-28 22:08 UTC, danielmaharry-okta requested changes
Hi Rob, 
A few general comments
- Decide how you are capitalising `IDXAuthenticationWrapper` and then use it throughout the guide. The instance of the class is called idxAuth.. but the class itself is IDXAuth... As you can't assume the user is going to call the instance of the class the same thing, I'd suggest using IDXAuth...
- The graphics all have drop shadows on them. I thought Chris didnt want this?
- Alt text and titles for images can be richer. I've given an example and leave it to you to complete the rest.
- Mention Thymeleaf once in a note at the top somewhere. You mention it four times. Perhaps in the software versions bit as people will read that to see if their systems are valid.
- Not sure how much I like saying the "The sample app does this" twelve times during the guide. I don't think you need to say the code comes from the sample app at all as long as it is representative of the code needed to do the thing.
- Check for long code lines overflowing to the right and split them onto two lines or more as necessary.

2022-04-28 22:08 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +The returned `PublicKeyCredential` object contains the signature and other binary formatted data that you need to convert to strings before sending it back to the Okta servers. The sample app uses cl
```suggestion
The returned `PublicKeyCredential` object contains the signature and other binary-formatted data that you need to convert to strings before sending it back to the Okta servers. The sample app uses client-side javascript to convert this data into a variable.
```

2022-04-28 22:08 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +1. First, send the converted signature data to the Okta SDK. The sample app sends the data through an HTTP Post request from the client browser to the server.
```suggestion
1. Send the converted signature data from the client browser to the server side of your web application.
```

2022-04-28 22:08 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +2. Next, send the data to `IDXAuthenticationWrapper.verifyWebAuthn()` to have the server validate the signature corresponding to the challenge and public key.
```suggestion
2. Call `IDXAuthenticationWrapper.verifyWebAuthn()` to have the server validate the signature corresponding to the challenge and public key.
```

2022-04-28 22:08 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +3. Depending on the org configuration, the `AuthenticationResponse` from `idxAuthenticationWrapper.verifyWebAuthn()` can return an `authenticationStatus` of `SUCCESS` along with token information, or
```suggestion
3. Depending on the org configuration, the `AuthenticationResponse` returned by `idxAuthenticationWrapper.verifyWebAuthn()` can contain an `authenticationStatus` of `SUCCESS` along with token information, or another status indicating there are additional remediation steps to complete.
```

2022-04-29 14:24 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +The first step is to initiate a use case that requires authentication. This guide uses the sign-in with username and password flow that is initiated with calls to `IDXAuthenticatorWrapper.begin()`, `
updated

2022-04-29 14:30 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +After the user submits their password, make a call to `IDXAuthenticationWrapper.verifyAuthenticator()` to verify their password. If you configure your Okta org as detailed in [Configuration updates](
updated.

2022-04-29 14:37 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsummary.md
> +![Sequence diagram showing WebAuthn enrollment summary](/img/authenticators/authenticators-webauthn-java-enrollment-summary.png)
Alex made the update

2022-04-29 14:37 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsummary.md
> +![Sequence diagram showing WebAuthn challenge summary](/img/authenticators/authenticators-webauthn-java-challenge-summary.png)
Alex made the update

2022-04-29 14:39 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +The first step is to initiate a use case that requires authentication. This guide uses the sign-in with username and password flow that is initiated with calls to `IDXAuthenticatorWrapper.begin()`, `
updated.

2022-04-29 14:41 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +AuthenticationResponse beginResponse = idxAuthenticationWrapper.begin();
I'm confused over this one. This code block is identical in both flows.

2022-04-29 14:43 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +After the user submits their password, make a call to `IDXAuthenticationWrapper.verifyAuthenticator()` to verify their password. If you configure your Okta org as detailed in [Configuration updates](
I changed it to authenticate().

2022-04-29 14:44 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +Authenticator selection page example from the sample app:
updated.

2022-04-29 14:46 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +                    authenticators.stream().filter(auth -> auth.getType().equals("webauthn")).findFirst();
updated.

2022-04-29 14:50 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +Redirect the user to a page that creates the WebAuthn credentials and allow this page access to the `AuthenticationResponse` properties. Using the sample app as guide, access these properties with th
removed.

2022-04-29 14:53 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +1. Browser prompts the user to choose an authenticator.
updated.

2022-04-29 15:00 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +2. After the user chooses the authenticator, the device's local authenticator asks for consent to create the credentials. In the following example, the **Touch ID** authenticator prompts the user for
A local authenticator can be the platform or a roaming authenticator like a yubi key. That content did come from a reputable source but it does sound odd. Without needing to get to low level, I changed "device's local authenticator asks for conset" to just "device asks for consent".

2022-04-29 15:40 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +The returned `PublicKeyCredential` object contains the signature and other binary formatted data that you need to convert to strings before sending it back to the Okta servers. The sample app uses cl
updated.

2022-04-29 15:40 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +When the user selects the WebAuthn option and clicks submit, call `IDXAuthenticatorWrapper.enrollAuthenticator()` passing in `ProceedContext` and the authenticator Id returned from `AuthenticationRes
updated.

2022-04-29 15:45 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +3. Depending on the org configuration, the `AuthenticationResponse` from `idxAuthenticationWrapper.verifyWebAuthn()` can return an `authenticationStatus` of `SUCCESS` along with token information, or
updated.

2022-04-29 15:46 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +When the user selects the WebAuthn option and clicks submit, call `IDXAuthenticatorWrapper.enrollAuthenticator()` passing in `ProceedContext` and the authenticator Id returned from `AuthenticationRes
updated.

2022-04-29 15:48 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +When the user selects the WebAuthn option and clicks submit, call `IDXAuthenticatorWrapper.enrollAuthenticator()` passing in `ProceedContext` and the authenticator Id returned from `AuthenticationRes
updated.

2022-04-29 15:49 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +The `AuthenticationResponse` object from `IDXAuthenticatorWrapper.enrollAuthenticator()` has `authenticationStatus` set to `AWAITING_AUTHENTICATOR_VERIFICATION`, which indicates the user must verify
Updated.

2022-04-29 15:50 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +Redirect the user to a page that verifies the WebAuthn credentials. Allow this page access to `AuthenticationResponse.webAuthnParams.currentAuthenticator.contextualData.challengeData` and  `Authentic
updated.

2022-04-29 15:52 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +2. Set client-side javascript variables. The sample app uses the [Thymeleaf](https://www.thymeleaf.org/) template engine to set these variables.
They are used to either get or create the credential. I've updated the text to give more context.

2022-04-29 15:53 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +    The following example renders the previous javascript code snippet.
Updated.

2022-04-29 15:53 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +Call the Web Authentication API's `navigator.credentials.get()` in the client browser and pass in the `CredentialRequestOptions` object created in the previous step.
updated.

2022-04-29 15:54 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +The returned `PublicKeyCredential` object contains the signature and other binary formatted data that you need to convert to strings before sending it back to the Okta servers. The sample app uses cl
updated.

2022-04-29 15:55 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +2. Next, send the data to `IDXAuthenticationWrapper.verifyWebAuthn()` to have the server validate the signature corresponding to the challenge and public key.
Updated.

2022-04-29 15:55 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +3. Depending on the org configuration, the `AuthenticationResponse` from `idxAuthenticationWrapper.verifyWebAuthn()` can return an `authenticationStatus` of `SUCCESS` along with token information, or
Updated.

2022-04-29 17:14 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +After the user submits their password, make a call to `IDXAuthenticationWrapper.verifyAuthenticator()` to verify their password. If you configure your Okta org as detailed in [Configuration updates](
I confirmed with Arvind. The Java sample app can either be identifier first or require username and password based on an org setting. In this guide we are discussing the username and pwd flow.

2022-04-29 21:16 UTC, danielmaharry-okta approved these changes
LGTM!

2022-05-19 22:42 UTC, susanharper-okta reviewed
couple things. additionally, some comments about text in the graphics:

authenticators-webauthn-java-challenge-summary.png

id -> ID

Step 4: (I think?) Call enrollAuthenticator passing in authenticator ID

Step 6: (I think?) Set up age with challenge and credential ID

Verify that

Step 7: Verify that credential ID matches domain name

avoid e.g. - use example: and finger print -> fingerprint

Step 7: User initiates verification (example: fingerprint)

-------------
authenticators-webauthn-java-enrollment-summary.png

id -> ID

Step 4: (I think) Call enrollAutenticator passing in authenticator ID

avoid e.g. - use example:, Id -> ID, and finger print -> fingerprint

Step 7: User chooses authenticator (example: Touch ID)

Step 7: User initiates verification (example: fingerprint)

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +Start the challenge flow with calls to `IDXAuthenticatorWrapper.begin()` and `AuthenticationResponse.getProceedContext()`. Then send username and password to the Okta server with `IDXAuthenticatorWra
```suggestion
Start the challenge flow with calls to `IDXAuthenticatorWrapper.begin()` and `AuthenticationResponse.getProceedContext()`. Then send the username and password to the Okta server with `IDXAuthenticatorWrapper.authenticate()`.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +3. Depending on the org configuration, the `AuthenticationResponse` returned by `IDXAuthenticationWrapper.verifyWebAuthn()` may contain `authenticationStatus` of `SUCCESS` along with token informatio
```suggestion
3. Depending on the org configuration, the `AuthenticationResponse` returned by `IDXAuthenticationWrapper.verifyWebAuthn()` may contain `authenticationStatus` of `SUCCESS` along with token information or another status to indicate that there are further remediation steps to complete.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +The `AuthenticationResponse` object returned by `IDXAuthenticatorWrapper.enrollAuthenticator()` has `authenticationStatus` set to `AWAITING_AUTHENTICATOR_VERIFICATION`, indicating the user must verif
```suggestion
The `AuthenticationResponse` object returned by `IDXAuthenticatorWrapper.enrollAuthenticator()` has `authenticationStatus` set to `AWAITING_AUTHENTICATOR_VERIFICATION`, which indicates that the user must verify their WebAuthn credentials. `AuthenticationResponse` returns the challenge and other information needed to verify the WebAuthn credentials on the user's device.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +2. Set client-side javascript variables to values originating from `currentAuthenticator`. These variables are used later to create the credential.
```suggestion
2. Set client-side javascript variables to values that originate from `currentAuthenticator`. These variables are used later to create the credential.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +1. The browser prompts the user to choose the type of WebAuthn authenticator they are using. For example, a portable hardware authenticator such as a USB security key, or a software-based authenticat
```suggestion
1. The browser prompts the user to choose the type of WebAuthn authenticator that they are using. For example: a portable hardware authenticator such as a USB security key or a software-based authenticator such as a fingerprint scanner
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +3. The private and public key pairs are created. The private key is stored internally on the device and linked to the user and domain name. Specifically, `navigator.credentials.create()` returns an o
```suggestion
3. The private and public key pairs are created. The private key is stored internally on the device and linked to the user and domain name. Specifically, `navigator.credentials.create()` returns an object of type `PublicKeyCredential` that contains the public key, credential ID, and other information used to associate the new credential with the server and browser.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +The returned `PublicKeyCredential` object contains the signature and other binary-formatted data you need to convert to strings before sending it back to the Okta servers.
```suggestion
The returned `PublicKeyCredential` object contains the signature and other binary-formatted data that you need to convert to strings before sending it back to the Okta servers.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/enrollmentintegrationsteps.md
> +3. Depending on the org configuration, the `AuthenticationResponse` returned by `IDXAuthenticationWrapper.verifyWebAuthn()` may contain `authenticationStatus` of `SUCCESS` along with token informatio
```suggestion
3. Depending on the org configuration, the `AuthenticationResponse` returned by `IDXAuthenticationWrapper.verifyWebAuthn()` may contain `authenticationStatus` of `SUCCESS` along with token information, or another status to indicate that there are further remediation steps to complete.
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/orgconfigurepwdonly.md
> +[An Okta org already configured for a password-only use case](/docs/guides/oie-embedded-common-org-setup/java/main/#set-up-your-okta-org-for-a-password-factor-only-use-case)
```suggestion
[An Okta org already configured for a password only use case](/docs/guides/oie-embedded-common-org-setup/java/main/#set-up-your-okta-org-for-a-password-factor-only-use-case)
```

2022-05-19 22:42 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/softwareversions.md
> +* Your browser must be up-to-date to use WebAuthn. The Embedded SDK sample app for the Java SDK only supports Chrome (version 88 and higher).
```suggestion
* Your browser must be up to date to use WebAuthn. The Embedded SDK sample app for the Java SDK only supports Chrome (version 88 and higher).
```

2022-06-10 20:38 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/java/challengeintegrationsteps.md
> +Start the challenge flow with calls to `IDXAuthenticatorWrapper.begin()` and `AuthenticationResponse.getProceedContext()`. Then send username and password to the Okta server with `IDXAuthenticatorWra
updated

2022-06-14 15:15 UTC, merged