OKTA-490569 add smart card idp
okta/okta-developer-docs pull request #3303
Opened 2022-04-29 19:39 UTC by vanngo-okta

## Description:
- **What's changed?** Add Smart Card IdP to the "Add an Identity Provider" section
- **Is this PR related to a Monolith release?** No
### Resolves:

* [OKTA-490569](https://oktainc.atlassian.net/browse/OKTA-490569)

2022-04-29 21:40 UTC, vanngo-okta commented
Lucas Gomes (CIAM Technical Marketing Manager), who originally requested this addition, approved the changes.

2022-05-03 22:14 UTC, vanngo-okta commented
John Baldo and Megha Rastogi approved via Slack.

2022-05-04 01:42 UTC, robertnicolo-okta requested changes
Looks good except for one feedback item.

2022-05-04 01:42 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/add-an-external-idp/smartcard/index.md
> +Okta supports smart cards with an x.509 compliant digital certificate, such as a personal identity verification card, as a primary authentication factor to sign in to Okta. To configure this feature
```suggestion
Okta supports smart cards with an X.509 compliant digital certificate, such as a personal identity verification card, as a primary authentication factor to sign in to Okta. To configure this feature in Okta, you need to add Smart Card as an external Identity Provider.
```

2022-05-04 13:17 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/guides/add-an-external-idp/smartcard/index.md
> +Okta supports smart cards with an x.509 compliant digital certificate, such as a personal identity verification card, as a primary authentication factor to sign in to Okta. To configure this feature
Committed your suggestion. Thanks!

2022-05-04 13:28 UTC, robertnicolo-okta approved these changes
lgtm

2022-05-04 21:19 UTC, merged