TBS OKTA-488936 Blacklist/whitelist from RNs
okta/okta-developer-docs pull request #3317
Opened 2022-05-04 15:44 UTC by brentschaus-okta

## Description
- **What's changed?** As part of the inclusive language efforts, removing "blacklist" and "whitelist" from RNs. Also, updating the spelling in existing docs from "allow list" to "allowlist" and "block list" to "blocklist".
- **Is this PR related to a Monolith release?**No.

### Resolves:

* [OKTA-488936](https://oktainc.atlassian.net/browse/OKTA-488936)

2022-05-04 15:54 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
> +* Make sure that in your app configuration, the `redirect_uri` is an absolute URI and that it is allowlisted by specifying it in [Trusted Origins](/docs/reference/api/trusted-origins/).
```suggestion
* Make sure that in your app configuration, the `redirect_uri` is an absolute URI and that it is allowed by specifying it in [Trusted Origins](/docs/reference/api/trusted-origins/).
```

2022-05-04 15:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/sign-users-out/main/aspnetcore3/addbaseuri.md
> +* **Option 1:** Allowlist the post sign-out URL in your Okta application settings in the Admin Console.
```suggestion
* **Option 1:** Allow the post sign-out URL in your Okta application settings in the Admin Console.
```

2022-05-04 15:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/authn/index.md
> +* The **public IP address** of your [trusted application](#trusted-application) must be [allowlisted as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's or
```suggestion
* The **public IP address** of your [trusted application](#trusted-application) must be [allowed as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's original IP address with the `X-Forwarded-For` HTTP header.
```

2022-05-04 15:57 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/authn/index.md
> +* The **public IP address** of your [trusted application](#trusted-application) must be [allowlisted as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's or
```suggestion
* The **public IP address** of your [trusted application](#trusted-application) must be [allowed as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's original IP address with the `X-Forwarded-For` HTTP header.
```

2022-05-04 15:57 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/authn/index.md
> +* The **public IP address** of your [trusted application](#trusted-application) must be [allowlisted as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's or
```suggestion
* The **public IP address** of your [trusted application](#trusted-application) must be [allowed as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's original IP address with the `X-Forwarded-For` HTTP header.
```

2022-05-04 15:59 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/factors/index.md
> +> **Notes:** The client `IP Address` and `User Agent` of the HTTP request is automatically captured and sent in the push notification as additional context.<br><br>You should [always send a valid Use
```suggestion
> **Notes:** The client `IP Address` and `User Agent` of the HTTP request is automatically captured and sent in the push notification as additional context.<br><br>You should [always send a valid User-Agent HTTP header](/docs/reference/core-okta-api/#user-agent) when verifying a push Factor.<br><br> The **public IP address** of your application must be [allowed as a gateway IP address](/docs/reference/core-okta-api/#ip-address) to forward the user agent's original IP address with the `X-Forwarded-For` HTTP header.
```

2022-05-04 16:07 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/release-notes/2018/index.md
> +* Using the [Zones API](/docs/reference/api/zones/) to modify an existing zone that is blocked, removed the block and converted it to a normal IP Zone. (OKTA-176610)
```suggestion
* Using the [Zones API](/docs/reference/api/zones/) to modify an existing zone that is blocked, removed the zone from the blocklist and converted it to a normal IP Zone. (OKTA-176610)
```

2022-05-04 16:20 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +* [Use a dynamic group allowlist with the Org Authorization Server](#use-a-dynamic-group-allowlist-with-the-org-authorization-server)
```suggestion
* [Use a dynamic group allowlist with the Org Authorization Server](#use-a-dynamic-group-allow-list-with-the-org-authorization-server)
```

2022-05-04 20:08 UTC, robertnicolo-okta requested changes
Hi Brent, 
Changes look good. Two main items for you:

1. We need to fix the areas where the headers are currently being referenced. The links won't work because the header name has changed.
2. Update existing conductor.yml entries that point to the old header. I would confirm with others all the changes you need to make to this file.

2022-05-04 20:08 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +## Use a static group allowlist with the Org Authorization Server
Referenced in conductor.yml and another file

2022-05-04 20:08 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> -## Use a static group allow list with a Custom Authorization Server
Referenced in other areas.

2022-05-04 20:50 UTC, vanngo-okta reviewed
Hi Brent, 
Robert is correct about the headers and the external links/conductor.yml files. I'm really sorry for not telling you to avoid headers. Maybe we have to revert all the header/title changes to avoid all the follow up work in the conductor files? I reviewed all the changes to the release notes, and they are good. For the /api/idps/index.md file updates, I've made some of the same changes in another PR for that file, so you will have conflicts when merging. Perhaps revert the changes for the /api/idps/index.md file as well? Again, I'm truly sorry for all this extra work :-(

2022-05-05 00:22 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/idps/index.md
> +| `APPEND`    | Adds a User to any Group defined by the IdP as a value of the `sourceAttributeName` array that matches the name of the Group in the allowlist defined in the `filter` | Unchanged
```suggestion
| `APPEND`    | Adds a User to any Group defined by the IdP as a value of the `sourceAttributeName` array that matches the name of the allow listed Group defined in the `filter` | Unchanged                                                                                     | Unchanged                                          | Unchanged                                    |
```

2022-05-05 00:22 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/idps/index.md
> +| `SYNC`      | Group memberships are mastered by the IdP as a value of the `sourceAttributeName` array that matches the name of the Group in the allowlist defined in the `filter` | Removed if not de
```suggestion
| `SYNC`      | Group memberships are mastered by the IdP as a value of the `sourceAttributeName` array that matches the name of the allow listed Group defined in the `filter` | Removed if not defined by the IdP in `sourceAttributeName` and matching name of the Group in `filter` | Unchanged                                          | Unchanged                                    |
```

2022-05-05 00:23 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/idps/index.md
> +Defines an allowlist of Group membership to restrict which Users are available for account linking by an IdP.
```suggestion
Defines an allow list of Group membership to restrict which Users are available for account linking by an IdP.
```

2022-05-05 00:24 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/idps/index.md
> +| include  | Specifies the allowlist of Group identifiers to match against | Array of String (Group IDs)  | TRUE     | FALSE    |
```suggestion
| include  | Specifies the allow list of Group identifiers to match against | Array of String (Group IDs)  | TRUE     | FALSE    |
```

2022-05-05 00:26 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/index.md
> +title: Customize tokens returned from Okta with a dynamic allowlist
```suggestion
title: Customize tokens returned from Okta with a dynamic allow list
```

2022-05-05 00:27 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +title: Customize tokens returned from Okta with a dynamic allowlist
```suggestion
title: Customize tokens returned from Okta with a dynamic allow list
```

2022-05-05 00:27 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +## About the dynamic allowlist
```suggestion
## About the dynamic allow list
```

2022-05-05 00:28 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +## Add a Groups claim with a dynamic allowlist
```suggestion
## Add a Groups claim with a dynamic allow list
```

2022-05-05 00:28 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +## Use a dynamic group allowlist with the Org Authorization Server
```suggestion
## Use a dynamic group allow list with the Org Authorization Server
```

2022-05-05 00:29 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
> +## Use a dynamic group allowlist with a Custom Authorization Server
```suggestion
## Use a dynamic group allow list with a Custom Authorization Server
```

2022-05-05 00:30 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/index.md
> +title: Customize tokens returned from Okta with a static allowlist
```suggestion
title: Customize tokens returned from Okta with a static allow list
```

2022-05-05 00:30 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +title: Customize tokens returned from Okta with a static allowlist
```suggestion
title: Customize tokens returned from Okta with a static allow list
```

2022-05-05 00:30 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +## About the static allowlist
```suggestion
## About the static allow list
```

2022-05-05 00:31 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +## Add a Groups claim with a static allowlist
```suggestion
## Add a Groups claim with a static allow list
```

2022-05-05 00:32 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +#### Use group functions for static group allowlists
```suggestion
#### Use group functions for static group allow lists
```

2022-05-05 00:32 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +## Use a static group allowlist with the Org Authorization Server
```suggestion
## Use a static group allow list with the Org Authorization Server
```

2022-05-05 00:33 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
> +## Use a static group allowlist with a Custom Authorization Server
```suggestion
## Use a static group allow list with a Custom Authorization Server
```

2022-05-05 00:34 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/zones/index.md
> +### Create a Blocklist Network Zone
```suggestion
### Create a Block List Network Zone
```

2022-05-05 00:35 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/api/zones/index.md
> +Creates a new Blocklist Network Zone
```suggestion
Creates a new Block List Network Zone
```

2022-05-05 00:39 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
> -* Okta sends tokens and authorization codes to a redirect URI (bound to the application's client ID) only if it is on the allow list. Therefore, limit this list to URIs in active use.
@robertnicolo-okta We decided to roll back the changes to all headers and titles, so we don't need to update the navbar.const.js file.

2022-05-05 00:40 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
> -* Okta sends tokens and authorization codes to a redirect URI (bound to the application's client ID) only if it is on the allow list. Therefore, limit this list to URIs in active use.
Hi Robert, we decided to roll back all changes to titles and headers so we don't need to update the navbar.const.js file. Thanks!

2022-05-05 01:02 UTC, vanngo-okta approved these changes
LGTM! 🚀 
Thank you for doing all these updates! 👏

2022-05-05 13:48 UTC, merged