Final PR for Java Authenticator Guides
okta/okta-developer-docs pull request #3421
Opened 2022-06-20 15:30 UTC by danielmaharry-okta

## Description:
- **What's changed?** Final PR for the Java versions of five guides. All guides have been final edited already. These were previously blocked by an issue with the Device Context feature in Identity Engine and so were grouped together for quick release once unblocked. It has been agreed to push these live despite the DC issue remaining unresolved. Okta Verify for now is commented out in situ, with a warning in its place.

- **Is this PR related to a Monolith release?** No

### Resolves:

* [SSPR with Embedded Auth integration guide](https://oktainc.atlassian.net/browse/OKTA-459209)
* [Google authenticator integration guide](https://oktainc.atlassian.net/browse/OKTA-459226)
* [Okta Email integration guide](https://oktainc.atlassian.net/browse/OKTA-459283)
* [Okta Verify integration guide](https://oktainc.atlassian.net/browse/OKTA-459398)
* [WebAuthn integration guide](https://oktainc.atlassian.net/browse/OKTA-459404)

2022-06-22 17:31 UTC, robertnicolo-okta requested changes
See each feedback item for more details.

2022-06-22 17:31 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +> **NOTE:**  This state is skipped if your application's sign-on policy contains only one factor.
```suggestion
> **Note:**  This state is skipped if your application's sign-on policy contains only one factor.
```

2022-06-22 17:31 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +* Sign user in
The See Also section is empty

2022-06-22 17:31 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/siw.md
> +![Screenshot of password reset page](/img/advanced-use-cases/java-custom-pwd-recovery-custom-siw-reset-pwd-page.png "Password Reset Page")
screenshot missing border

2022-06-24 15:03 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-okta-email/main/java/integratechallengemagiclink.md
> +### 4. Display a list of possible authenticators
changed

2022-06-24 15:14 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-okta-email/main/java/integratechallengemagiclink.md
> +      "Unsupported factor type selected: " + factorType);
@robertnicolo-okta  I've deleted this section's text and replaced it with the text from the same area in the aspnet guide. This covers both options and does not mention polling.

2022-06-24 15:20 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +The challenge flow follows the same first four steps as the [enrollment flow](#integrate-sdk-for-authenticator-enrollment):
@robertnicolo-okta  We talked about this briefly already.

- If there are a number of steps which need to be documented but don't contribute to the actual flow, I compact them into one step. For example 1-3. Start flow and retrieve list of authenticators.  Steps 1 to 3 are written out in full in the text. 
- The only reason I'd abridge the text is if those steps are excatly the same as a flow covered earlier in the same document. For example in the Email authetnicator document I have "1 - 7. Sign in and get magic link email
First, the user attempts to sign in, initiating the email challenge flow. Next, they click the magic link that redirects them back to your app. These steps are identical to steps 1 - 7 in Integrate email challenge with magic links." 

I hope that's OK.

2022-06-24 15:21 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +> **NOTE:**  This state is skipped if your application's sign-on policy contains only one factor.
fixed

2022-06-24 15:22 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +* Sign user in
fixed.

2022-06-24 15:25 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/siw.md
> +![Screenshot of password reset page](/img/advanced-use-cases/java-custom-pwd-recovery-custom-siw-reset-pwd-page.png "Password Reset Page")
fixed

2022-06-24 15:49 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
> +The challenge flow follows the same first four steps as the [enrollment flow](#integrate-sdk-for-authenticator-enrollment):
There was one section (we just talked about) which you'll add links pointing to the other section. I'm going to LGTM to not hold you up.

2022-06-24 15:50 UTC, robertnicolo-okta approved these changes
lgtm

2022-06-24 16:27 UTC, merged