OKTA-552356 Move wireframes to common directory and rename
okta/okta-developer-docs pull request #3760
Opened 2022-11-24 16:19 UTC by danielmaharry-okta

## Description:
- **What's changed?** 
  - Moved wireframe diagrams from oie-embedded-sdk and pwd-optional guides to \img\wireframes common directory
  - Gave diagrams generic names for easy reuse
  - Used common HTML set out on https://www.figma.com/file/YH5Zhzp66kGCglrXQUag2E/%F0%9F%93%8A-Updated-Diagrams-for-Dev-Docs?node-id=2361%3A1870&t=ms6DWfQdUEUA7lAK-1

- **Is this PR related to a Monolith release?** No

### Netlify links (all lang variants)

Updated Nov 30

- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-new-sign-up-email/aspnet/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-sign-in-email/aspnet/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/android/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/aspnet/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-self-reg/aspnet/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/android/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/android/main/
- https://63872e871d4acf3ae95982bd--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-widget-sign-in-email/aspnet/main/

### Resolves:

* [OKTA-552356](https://oktainc.atlassian.net/browse/OKTA-552356)

2022-11-29 04:00 UTC, robertnicolo-okta requested changes
Hi Dan, awesome to see the wireframes cleaned up. I noticed a lot of broken image URLs in prod so this will help a lot. See the feedback items for more details.

2022-11-29 10:34 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/integrationsteps.md
> +![A sign-in form with fields for username and password and a sign in button](/img/wireframes/sign-in-form-username-and-password.png)
1. Have changed all image names to include word "form"
2. They all start with an action word. They all start with the name of the form in the actual wireframe. Except if they are widget mock ups
3. Have tweaked names to be consistent and include all field names

2022-11-29 11:05 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:06 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A choose your authenticator form with google and okta verify options and next, skip, and cancel buttons](/img/wireframes/choose-authenticator-google-okta-verify-with-skip-and-cancel.png)
fixed

2022-11-29 11:06 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/java/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:06 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/nodeexpress/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:07 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/react/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:07 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-sign-in-email/main/java/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:07 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-sign-in-email/main/react/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
fixed

2022-11-29 11:09 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-widget-sign-in-email/main/index.md
> +![The Okta Sign-In Widget's prompt to enter the code or click a link sent in an email to the user. Also a button to resend the email](/img/wireframes/widget-send-email-form.png)
fixed

2022-11-29 11:26 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A create account form with fields for first name, last name, and email address, and a create account button](/img/wireframes/create-account-first-last-name-email.png)
It was "Create Account" in the original wireframes that Chris created and we approved. I'm only using one version of this image. If we need to standardize on one name for the form and correct around it, how do we do that?

2022-11-29 11:30 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A choose your authenticator form with google and okta verify options and next, skip, and cancel buttons](/img/wireframes/choose-authenticator-google-okta-verify-with-skip-and-cancel.png)
All the wireframes use "Next" rather than "Submit".

2022-11-29 11:37 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/android/integrationsteps.md
> +![A choose your authenticator form with only a phone authenticator option, and next and skip buttons](/img/wireframes/choose-authenticator-phone-only-with-skip-option.png)
fixed. Switched to wireframe with no skip button

2022-11-29 11:53 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A create account form with fields for first name, last name, and email address, and a create account button](/img/wireframes/create-account-first-last-name-email.png)
This is the widget form. 
![image](https://user-images.githubusercontent.com/97525701/204522178-367e53de-86a8-4b74-957a-9baf923a61e0.png)

I will change the create account form to match this and rename it to sign up form

2022-11-29 12:03 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A choose your authenticator form with google and okta verify options and next, skip, and cancel buttons](/img/wireframes/choose-authenticator-google-okta-verify-with-skip-and-cancel.png)
All the wireframes are consistent with each other and use "Next".
The widget actually provides a button for each option, which seems overkill, so staying with "Next"

![image](https://user-images.githubusercontent.com/97525701/204524149-686a8ab8-b6a8-497d-bfa5-0fcee27865df.png)

2022-11-29 12:04 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-sign-in-email/main/aspnet/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
Widget uses a next button. I will change all four sign-in wireframes to have a next button.

![image](https://user-images.githubusercontent.com/97525701/204524416-40e3a720-9bc6-41f9-a4bb-1bde2ff0be4e.png)

2022-11-29 12:12 UTC, danielmaharry-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A sign-in form with a field for the username and links to the sign up and forgot your password forms](/img/wireframes/sign-in-form-username-only-sign-up-forgot-your-password-links.png)
Changed

2022-12-01 03:22 UTC, robertnicolo-okta commented on packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/aspnet/integrationsteps.md
> +![A create account form with fields for first name, last name, and email address, and a create account button](/img/wireframes/create-account-first-last-name-email.png)
Sign up button needs to be centered.

2022-12-01 03:27 UTC, robertnicolo-okta approved these changes
lgtm

2022-12-01 13:23 UTC, merged