API doc for perpetual account lockout prevention OIE
okta/okta-developer-docs pull request #3791
Opened 2022-12-06 22:42 UTC by yumingcao-okta

## Description:
- API doc for perpetual account lockout prevention OIE
- Yes, expected to be released end of January

### Resolves:

* [OKTA-553106](https://oktainc.atlassian.net/browse/OKTA-553106)

2022-12-07 19:26 UTC, vanngo-okta requested changes
Looks good! Just a few suggestions.

2022-12-07 19:26 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/users/index.md
> +| expand        | Valid value: `block`. If you have migrated to Okta Identity Engine, you can specify `blocks` to include account block details in the `_embedded` attribute. The embedded object will
```suggestion
| expand  <ApiLifecycle access="ie" />  | Valid value: `block`. If this parameter is specified, then account block details are included in the `_embedded` attribute. The returned embedded object is the same as the one returned by the [Get User Blocks](#get-user-blocks) operation. | Query        | String   | FALSE     |
```

2022-12-07 19:26 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/users/index.md
> +### Get User's Blocks
```suggestion
### Get User Blocks
```

2022-12-07 19:26 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/users/index.md
> +| id        | `id`, `login`, or `login shortname` (as long as it is unambiguous) of user | URL        | String   | TRUE     |
```suggestion
| id        | `id`, `login`, or `login shortname` (as long as it is unambiguous) of the user | URL        | String   | TRUE     |
```

2022-12-07 19:26 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/users/index.md
> +The object describes how the account is blocked from access. If `appliesTo` is `ANY_DEVICES`, the account is blocked for all devices. If `appliesTo` is `UNKNOWN_DEVICES`, the account is only [blocked
```suggestion
The User Block object describes how the account is blocked from access. If `appliesTo` is `ANY_DEVICES`, then the account is blocked for all devices. If `appliesTo` is `UNKNOWN_DEVICES`, then the account is only [blocked for unknown devices](/docs/reference/api/attack-protection/#user-lockout-settings-object).
```

2022-12-07 19:26 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/users/index.md
> +| type      | Type of the block. Valid values: `DEVICE_BASED` | String |
```suggestion
| type      | Type of the block. Valid value: `DEVICE_BASED` | String |
```

2023-01-12 22:01 UTC, yumingcao-okta commented
@vanngo-okta addressed your comments (for changes to existing API as we discussed), please re-review, thanks!

2023-01-16 18:53 UTC, vanngo-okta approved these changes
LGTM! 🚀

2023-06-14 14:00 UTC, vanngo-okta commented
Hi @yumingcao-okta, I'm putting this PR on hold until the feature releases. Please let us know. Thanks!

2023-09-12 17:03 UTC, merged