unique refresh token ID for token inline hoook
okta/okta-developer-docs pull request #4047
Opened 2023-03-21 23:24 UTC by susanharper-okta

## Description:
- **What's changed?** adding info around unique refresh token ID
- **Is this PR related to a Monolith release?** Yes 2023.04.0

### Resolves:

* [OKTA-578302](https://oktainc.atlassian.net/browse/OKTA-578302)

2023-03-21 23:25 UTC, acrolinxdevdocs-okta commented
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/token-hook/index.md](https://github.com/okta/okta-developer-docs/blob/cada1f65a1dd8fef46367c7c9318271e0073fda6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Ftoken-hook%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8d5e17f1-c951-4587-93cb-7d250c9df876) | 80  | 56  | 33  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.e44900b1-0907-42a5-b256-74181dc97026?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2023-03-21 23:25 UTC, susanharper-okta commented
/netlify preview

2023-03-22 00:07 UTC, susanharper-okta commented
/netlify preview

2023-03-23 19:19 UTC, anweshdatla-okta requested changes

2023-03-23 19:19 UTC, anweshdatla-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +In addition to adding custom claims, you can modify or remove an existing custom claim or an OIDC standard profile claim. You can update how long an access token or an ID token is valid. You can also
you can remove this doc change here.

2023-03-23 19:19 UTC, anweshdatla-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +In addition to adding custom claims, you can modify or remove an existing custom claim or an OIDC standard profile claim. You can update how long an access token or an ID token is valid. You can also
next to ###scopes you can add 
### data.refresh_token
Provides the refresh token ID, you could store the ID on the first access token request. When doing refresh token grant, its Id will match what was stored which should allow you to connect the two requests.

| Property | Description                   | Data Type                    |
|----------|-------------------------------|------------------------------|
| jti   | Refresh token ID | String     |

2023-03-23 19:19 UTC, anweshdatla-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +In addition to adding custom claims, you can modify or remove an existing custom claim or an OIDC standard profile claim. You can update how long an access token or an ID token is valid. You can also
@venkatviswanathan-okta please check if this text needs correction.

2023-03-23 19:22 UTC, anweshdatla-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +      }
```suggestion
    },
    "refresh_token": {
       "jti": "oarob4a0tckCkGcyo1d6"
    }
```

2023-03-23 20:42 UTC, acrolinxdevdocs-okta commented
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/token-hook/index.md](https://github.com/okta/okta-developer-docs/blob/7f150f5d4d33bc3756c0c3c3500b2348d069a433/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Ftoken-hook%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6853208a-7a9f-44d6-b282-d1b89f37a06d) | 80  | 57  | 34  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.a9901fd7-d88c-496b-a2ba-06dc0b83c515?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2023-03-23 20:43 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +Provides the refresh token ID that you can store on the first access token request. When you make the refresh token grant, the ID matches what was stored. This allows you to connect the two requests.
@venkatviswanathan-okta and @anweshdatla-okta - I updated the sentence

2023-03-23 20:52 UTC, acrolinxdevdocs-okta commented
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/token-hook/index.md](https://github.com/okta/okta-developer-docs/blob/d7ea52b07cfd57cfe77580ac122a025f3afc2027/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Ftoken-hook%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/45b2db3e-1764-4317-9ab0-256e6af3eaac) | 80  | 57  | 34  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.c12c75a5-e18f-4f66-a7ca-7f3f01703167?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2023-03-23 20:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +Provides the refresh token ID that you can store on the first access token request. When you make the refresh token grant, the ID matches what was stored. This allows you to connect the two requests.
@venkatviswanathan-okta and @anweshdatla-okta please review this. Thanks.

2023-03-23 20:54 UTC, anweshdatla-okta commented on packages/@okta/vuepress-site/docs/reference/token-hook/index.md
> +| jti        | Refresh token ID                         | Number    |
```suggestion
| jti        | Refresh token ID                         | String    |
```

2023-03-23 22:44 UTC, venkatviswanathan-okta approved these changes

2023-03-23 22:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/token-hook/index.md](https://github.com/okta/okta-developer-docs/blob/1dc29ee7ca8a92cadfdd4c0c82dc1fc59e2c538a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Ftoken-hook%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5a60ad14-3059-4ff2-b55e-52cc4667892a) | 80  | 57  | 34  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.9401e274-729a-492a-a612-8ab1126ece30?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2023-03-24 17:17 UTC, anweshdatla-okta approved these changes

2023-05-11 19:25 UTC, merged