Tl 619366
okta/okta-developer-docs pull request #4304
Opened 2023-08-07 18:34 UTC by tigerli-okta

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-619366](https://oktainc.atlassian.net/browse/OKTA-619366)

2023-08-07 21:03 UTC, tigerli-okta commented
/netlify preview

2023-08-09 17:31 UTC, vanngo-okta requested changes
Hi @tigerli-okta, your edits look good! I only have a few nits and can you please add the EA note at the bottom of the tables? Thank you!

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
>  > **Note:** `okta.apps.manageFirstPartyApps` permission is currently only supported as part of some [Standard IAM-based Roles](/docs/concepts/role-assignment/#iam-based-standard-role-types). You can'
```suggestion

> **Note:** `okta.apps.manageFirstPartyApps` permission is currently only supported as part of some [Standard IAM-based Roles](/docs/concepts/role-assignment/#iam-based-standard-role-types). You can't use it to create or update other roles.

> **Note:** `okta.devices.*` permissions are self-service Early Access. Turn on the **Enable custom admin roles for device permissions** feature from the **Settings** > **Feature** page in the Admin Console to access these permissions. See [Manage Early Access and Beta features](https://help.okta.com/okta_help.htm?id=ext_Manage_Early_Access_features).
```

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
> +| `okta.devices.read` <br><ApiLifecycle access="ea" />                              | Allows the admin to read device details and information
```suggestion
| `okta.devices.read` <br><ApiLifecycle access="ea" />                              | Allows the admin to read device details                                                                                                 | All Devices
```

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
> +| `okta.devices.lifecycle.deactivate` <br><ApiLifecycle access="ea" />                          | Allows the admin to deactivate devices. Deactivation causes a device to lose all device user links.
```suggestion
| `okta.devices.lifecycle.deactivate` <br><ApiLifecycle access="ea" />                          | Allows the admin to deactivate devices. When a device is deactivated, it loses all device user links.                                                                                                          | All Devices
```

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
> +|                         | All Devices     <br><ApiLifecycle access="ea" />                                                     | `orn:${partition}:directory:${yourOrgId}:devices`
Can you please add this note at the bottom of this table?

> **Note:** The All Devices resource is self-service Early Access. Turn on the **Enable custom admin roles for device permissions** feature from the **Settings** > **Feature** page in the Admin Console to use this resource. See [Manage Early Access and Beta features](https://help.okta.com/okta_help.htm?id=ext_Manage_Early_Access_features).

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/roles/index.md
> +|                         | All Devices     <br><ApiLifecycle access="ea" />                                                     | `orn:${partition}:directory:${yourOrgId}:devices`
Can you please add this note at the bottom of this table?

> **Note:** The All Devices resource is self-service Early Access. Turn on the **Enable custom admin roles for device permissions** feature from the **Settings** > **Feature** page in the Admin Console to use this resource. See [Manage Early Access and Beta features](https://help.okta.com/okta_help.htm?id=ext_Manage_Early_Access_features).

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/roles/index.md
> +| `okta.devices.read` <br><ApiLifecycle access="ea" />                              | Allows the admin to read device details and information
```suggestion
| `okta.devices.read` <br><ApiLifecycle access="ea" />                              | Allows the admin to read device details                                                                                                 | All Devices
```

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/roles/index.md
> +| `okta.devices.lifecycle.deactivate` <br><ApiLifecycle access="ea" />                          | Allows the admin to deactivate devices. Deactivation causes a device to lose all device user links.
```suggestion
| `okta.devices.lifecycle.deactivate` <br><ApiLifecycle access="ea" />                          | Allows the admin to deactivate devices. When a device is deactivated, it loses all device user links.                                                                                                          | All Devices
```

2023-08-09 17:31 UTC, vanngo-okta commented on packages/@okta/vuepress-site/docs/reference/api/roles/index.md
>  > **Note:** `okta.apps.manageFirstPartyApps` permission is only supported as part of some [Standard IAM-based Roles](/docs/concepts/role-assignment/#iam-based-standard-role-types). You can't use it t
```suggestion

> **Note:** `okta.apps.manageFirstPartyApps` permission is only supported as part of some [Standard IAM-based Roles](/docs/concepts/role-assignment/#iam-based-standard-role-types). You can't use it to create or update other roles.

> **Note:** `okta.devices.*` permissions are self-service Early Access. Turn on the **Enable custom admin roles for device permissions** feature from the **Settings** > **Feature** page in the Admin Console to access these permissions. See [Manage Early Access and Beta features](https://help.okta.com/okta_help.htm?id=ext_Manage_Early_Access_features).
```

2023-08-09 19:16 UTC, brentschaus-okta approved these changes
LGTM!

2023-08-09 20:18 UTC, vanngo-okta approved these changes
LGTM! 🚀

2023-08-16 18:05 UTC, merged