Direct Auth for SMS and Voice
okta/okta-developer-docs pull request #4445
Opened 2023-10-24 20:21 UTC by susanharper-okta

## Description:
- **What's changed?** Split out direct auth into it's own guide and then added SMS and Voice
- **Is this PR related to a Monolith release?** Yes 2023.11.0

### Resolves:

* [OKTA-650763](https://oktainc.atlassian.net/browse/OKTA-650763)

2023-10-24 20:21 UTC, susanharper-okta commented
/netlify preview

2023-10-24 20:52 UTC, susanharper-okta commented
/netlify preview

2023-10-25 21:17 UTC, susanharper-okta commented
/netlify preview

2023-10-26 15:14 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/overview.md
> +The steps in this guide focus on using the OOB flow with the Phone authenticator (SMS or Voice). Make sure that both **SMS** and **Voice call** are enabled.
nit: **SMS** and/or **Voice call**. They don't both need to be enabled if only one is being used

2023-10-26 15:15 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/overview.md
> +The steps in this guide focus on using the MFA OOB flow with the Phone authenticator (SMS or Voice). Make sure that both **SMS** and **Voice call** are enabled.
nit: "Make sure **SMS** and/or **Voice call** are enabled.". Both don't need to be enabled if only one is being used

2023-10-26 15:17 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/flow-diagram.md
> +1. Your app sends the username as a `login_hint` and the `channel_hint` to the Okta authorization server `/oob-authenticate` endpoint.
`channel_hint` should be "`channel_hint` with the value of `sms` or voice`"

2023-10-26 15:18 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/flow-diagram.md
> +1. Okta responds with the `oob_code`, `channel`, `binding_method=prompt`, and any other parameters required by the configured authenticator.
you don't need the ", and any other parameters required by the configured authenticator."

2023-10-26 15:19 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/flow-diagram.md
> +1. Your app sends the `binding_code` and `oob_code` in a `/token` request.
"sends the `binding_code`" -> "sends the OTP as the `binding_code`"

2023-10-26 15:22 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/flow-diagram.md
> +1. Your app sends a `/challenge` request with the `mfa_token` and the `channel_hint` values, and the `challenge_types_supported` (`http://auth0.com/oauth/grant-type/mfa-oob`) parameters to the Okta a
"Your app sends a `/challenge` request with the `mfa_token` and the `channel_hint` values" -> "Your app sends a `/challenge` request with the `mfa_token`, the `channel_hint` with value `sms` or `voice`"

2023-10-26 15:35 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/use-flow.md
> +- `channel_hint`: The out-of-band channel that the client wants to use. For example, Okta Verify Push.
instead of "For example", can it be "For Okta Verify, use `push`"

2023-10-26 15:38 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/use-flow.md
> +- `channel`: The type of out-of-band channel used.
maybe add, that it will be either `sms` or `voice`

2023-10-26 15:38 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/use-flow.md
> +- `binding_method`: The method used to bind the out-of-band channel with the primary channel. Supported value for `sms` or `voice` is `prompt`.
"Supported value for `sms` or `voice` is `prompt`" -> "Supported value when `channel` is `sms` or `voice` is `prompt`"

2023-10-26 15:40 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/nutrition.md
> +* A test user in your org enrolled in the Phone authenticator with both **SMS** and **Voice call** enabled
they don't need both SMS and Voice if theyare only using one

2023-10-26 15:41 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/nutrition.md
> +* A test user in your org that's enrolled in the Phone authenticator with both **SMS** and **Voice call** enabled
they don't need both SMS and Voice if they are only using one

2023-10-26 15:44 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/flow-diagram.md
> +1. Okta responds with the following parameters:
i don't see a bullet point list like this for any of the other pages. In the others it is just a comma separate list. Also "Any other parameters required by the configured authenticator." is not needed. That is just for okta verify

2023-10-26 15:47 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/flow-diagram.md
> +1. Your app sends a `/challenge` request with the `mfa_token` and the `channel_hint` values, and the `challenge_types_supported` (`http://auth0.com/oauth/grant-type/mfa-oob`) parameters to the Okta a
channel_hint should be "`channel_hint` with the value of `sms` or `voice`" and `challenge_types_supported` can be `challenge_types_supported=http://auth0.com/oauth/grant-type/mfa-oob`

2023-10-26 15:48 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/flow-diagram.md
> +1. Your app sends the `binding_code` and `oob_code` in a `/token` request.
"sends the binding_code" -> "sends the OTP as the binding_code"

2023-10-26 15:56 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/use-flow.md
> +- `client_id`: Matches the client ID of the mobile application that you created in the [Set up your app](#set-up-your-app) section. You can find it at the top of your app's **General** tab.
why did you make this update? In fact it could just be removed to "the application"

2023-10-26 19:45 UTC, susanharper-okta commented
/netlify preview

2023-10-26 20:03 UTC, dannavarro-okta requested changes
added a few more comments. They are all very minor.

2023-10-26 20:03 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/flow-diagram.md
> +   * `challenge_type`
`challenge_type=http://auth0.com/oauth/grant-type/mfa-oob`

2023-10-26 20:03 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/flow-diagram.md
> +   >**Note:** See [MFA OOB grant type](https://developer.okta.com/docs/api/openapi/okta-oauth/oauth/tag/OrgAS/#tag/OrgAS/operation/token).
same thing, can remove

2023-10-26 20:03 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/flow-diagram.md
> +    * `login_hint=${username}`
don't think you need the place holder here

2023-10-26 20:03 UTC, dannavarro-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/flow-diagram.md
> +    * `channel`
`channel` with a value of `sms` or `voice.

2023-10-26 21:00 UTC, dannavarro-okta approved these changes
none of my comments are blockers. thanks for all the work on reorganzing these pages. LGTM

2023-10-26 21:59 UTC, susanharper-okta commented
/netlify preview

2023-10-31 18:01 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/use-flow.md
> +- `binding_method`: The method used to bind the out-of-band channel with the primary channel. Supported value for `sms` or `voice` is `prompt`.
Match to `e` if accepted.

2023-10-31 18:02 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/use-flow.md
> +- `login_hint`: The username (email) of a user registered with Okta
```suggestion
- `login_hint`: The email username of a registered Okta user.
```

2023-10-31 18:04 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +> **Note:** See [About MFA authenticators](https://help.okta.com/okta_help.htm?type=oie&id=csh-configure-authenticators) for more information on authenticators, and primary and secondary factors. See
Would this work better as bullets?
```suggestion
> **Note:** 
>
> * See [About MFA authenticators](https://help.okta.com/okta_help.htm?type=oie&id=csh-configure-authenticators) for more information on authenticators, and primary and secondary factors. 
>
> * See [Configure a global session policy and authentication policies](https://developer.okta.com/docs/guides/configure-signon-policy/main/) for more information on configuring primary and secondary factor conditions.
```

2023-10-31 18:07 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +Direct authentication grant type flows use passwordless authentication, such as using Okta Verify, SMS, or signing in with email. You need a non-password authenticator enabled like <StackSnippet snip
```suggestion
Direct authentication grant type flows use passwordless authentication, such as using Okta Verify, SMS, or signing in with email. To use the direct authentication <StackSnippet snippet="granttype" inline /> flow, you must enable a non-password authenticator such as <StackSnippet snippet="authenticator" inline />.
```

2023-10-31 18:09 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +1. Select **Security** > **Authenticators** to view the available authenticators.
```suggestion
1. Go to **Security** > **Authenticators** to view the available authenticators.
```

2023-10-31 18:10 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +1. Do the following if <StackSnippet snippet="authenticator" inline /> isn't in the list:
```suggestion
1. If <StackSnippet snippet="authenticator" inline /> isn't listed:
```

2023-10-31 18:25 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +    * Select the **Enrollment** tab.
Reorg this a bit.
```suggestion
1. Verify the status of the authenticator.
    * Select the **Enrollment** tab.
    * Identify the authenticator, and verify....
1. If the authenticator is set to **Disabled**, enable the authenticator. 
    * Click **Edit** for the Default Policy 
    * Select **Optional** from the dropdown box for the authenticator
    * Click **Update Policy**.
```

2023-10-31 18:26 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +To use the <StackSnippet snippet="granttype" inline /> flow, both your client app and the [Okta authorization server](/docs/concepts/auth-servers/) that you're using with the app must have the <Stack
```suggestion
To use the <StackSnippet snippet="granttype" inline /> flow, both your client app and the [Okta authorization server](/docs/concepts/auth-servers/) used with the app must enable the <StackSnippet snippet="granttype" inline /> grant type.
```

2023-10-31 18:26 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +If your Okta org uses Identity Engine, then the <StackSnippet snippet="granttype" inline /> grant type is automatically configured in your org authorization server. For custom authorization servers t
```suggestion
If your Okta org uses Identity Engine, the <StackSnippet snippet="granttype" inline /> grant type is automatically configured in your org authorization server. For custom authorization servers used with your app, you must enable <StackSnippet snippet="granttype" inline />:
```

2023-10-31 18:27 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +2. On the **Authorization Servers** tab, select the pencil icon next to the authorization server that you want to use.
```suggestion
2. On the **Authorization Servers** tab, click the pencil icon next to the related authorization server.
```

2023-10-31 18:28 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +4. Select the pencil icon from the **Actions** column for the **Default Policy Rule**.
```suggestion
4. Click the pencil icon from the **Actions** column for the **Default Policy Rule**.
```

2023-10-31 18:29 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +    If you aren’t using the Default Policy for your client app that requires the <StackSnippet snippet="granttype" inline /> grant, select the policy that applies to your app.
```suggestion
    > **Note**: If you're using a different policy for your app, edit that policy instead.
```

2023-10-31 18:33 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +1. Select **Applications** > **Applications** to view the current app integrations.
```suggestion
1. Go to **Applications** > **Applications** to view the current app integrations.
```

2023-10-31 18:35 UTC, isaacdurham-okta commented on packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
> +In direct authentication flows, the client tells the server which authenticator it wants to authenticate with through the grant type. However, the server can't grant a token until the client’s authen
```suggestion
In direct authentication flows, the client specifies a grant type that indicates the type of authenticator being used. However, the server can't grant a token until the client’s authentication policy is satisfied.
```

2023-10-31 21:23 UTC, susanharper-okta commented
/netlify preview

2023-10-31 21:47 UTC, susanharper-okta commented
/netlify preview

2023-11-01 13:39 UTC, isaacdurham-okta approved these changes

2023-11-08 17:47 UTC, merged