[OKTA-702250] Feature Lifecycle Management page
okta/okta-developer-docs pull request #4680
Opened 2024-02-29 00:59 UTC by annejuan-okta

## Description:
- **What's changed?** Updated various parts of the feature lifecycle management concept page, improving the Acrolinx score

### Resolves:

* [OKTA-702250](https://oktainc.atlassian.net/browse/OKTA-702250)

2024-02-29 00:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/e00db93042e31ecf3a69734ed317c94e83f6ce3e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7dc438e6-59d3-4745-a4ee-e56ccc1bd113) | 100  | 100  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b7dcd7da-03d9-4f25-a2a3-d0064456c78b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-02-29 01:01 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/fd82baf7cb697ad1e1e5cd89d7742fd1b13a246f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4d96731f-7c5d-405f-a0fd-251027523c62) | 100  | 100  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c37d7f43-0bca-41e6-bb06-a90568149e13?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-02-29 17:07 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/412b731944602acad4ea6cfa7372db35a60e8683/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/697e796c-faf0-4132-b547-94ac06c9fef4) | 100  | 100  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.2929fbbe-f786-479e-ab3f-526d7d8c86e9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-02-29 22:31 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/304963914047043b74ea0e19cb5836c8d423d5d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0f18d2d6-dcda-41a7-a62a-ec6db1ce25c5) | 100  | 100  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.909f8b81-3ec9-421f-9c4d-870c7f1d039f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-03-07 17:44 UTC, susanharper-okta reviewed
couple edits. LMK if you have questions and we can discuss.

2024-03-07 17:44 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +If Feature A has Feature B as a dependency, then Feature A can't be enabled if Feature B isn't enabled first. Conversely, Feature B has Feature A as one of its dependants. This means that Feature B c
```suggestion
If Feature A has Feature B as a dependency, then you can't enable Feature A unless you enable Feature B first. Conversely, Feature B has Feature A as one of its dependants. This means that you can't disable Feature B unless you disable Feature A first.
```

2024-03-07 17:44 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +Self-service features are features an Okta admin can directly enable or disable. Features that aren't self-service can only be enabled or disabled by getting in touch with Okta Support. The [Okta Fea
```suggestion
Self-service features are features that you can directly enable or disable. Contact [Okta Support](https://support.okta.com) to enable features that aren't self-service. The [Okta Features API](/docs/reference/api/features/) is used to list, enable, and disable self-service features.
```

2024-03-07 18:45 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/15877519d9c0ff62cba4b3e344ac6a9bb42d2203/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2f04a784-3d31-4847-8a02-ed6fd6254513) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.4a8e31dd-b257-42ed-82d8-a9ba62c873ee?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-03-07 18:45 UTC, annejuan-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +> **Note:** A Beta feature marked as self-service will stay as self-service, even if it's closed and temporarily unavailable to be enabled. For example, if an [open Beta](#beta-features) transitions
I actually went back and forth on whether this should be present or future tense. I'll try to keep this in mind for the future.

2024-03-07 19:17 UTC, grahamsmith-okta approved these changes
Recommend using the American spelling of "dependent" (instead of with the 'a')

Otherwise good to go

2024-03-07 19:17 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +This page covers a few key concepts that underpin the [Okta Features API](/docs/reference/api/features/). The Features API allows you to manage self-service features, their feature dependants, and th
```suggestion
This page covers a few key concepts that underpin the [Okta Features API](/docs/reference/api/features/). The Features API allows you to manage self-service features, their feature dependents, and their feature dependencies. For Beta features, special restrictions apply to the behavior of the API.
```

2024-03-07 19:17 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +* Feature D has one dependant: Feature A.
```suggestion
* Feature D has one dependent: Feature A.
```

2024-03-07 19:17 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +Features might have dependencies and dependants. Dependencies are other features that the feature relies on, whereas dependants are features that rely on the feature.
```suggestion
Features might have dependencies and dependents. Dependencies are other features that the feature relies on, whereas dependents are features that rely on the feature.
```

2024-03-07 19:17 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +If Feature A has Feature B as a dependency, then you can't enable Feature A unless you enable Feature B first. Conversely, Feature B has Feature A as one of its dependants. This means that you can't
```suggestion
If Feature A has Feature B as a dependency, then you can't enable Feature A unless you enable Feature B first. Conversely, Feature B has Feature A as one of its dependents. This means that you can't disable Feature B unless you disable Feature A first.
```

2024-03-07 19:22 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/9657f7e21f215a3404e601f7e439b91b28c8c5db/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2000389-ab81-4358-bdd6-3c3fc814d346) | 100  | 45  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3dc04159-588f-4763-8c6b-f5d7bbbc62a2?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-03-07 19:30 UTC, grahamsmith-okta requested changes

2024-03-07 19:30 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
> +Though all available Beta features qualify as "self-service", Betas are either open or closed. You can enable or disable open Betas using the API. But, you can only disable closed Betas. If a feature
```suggestion
Though all available Beta features qualify as "self-service," Betas are either open or closed. You can enable or disable open Betas using the API. But, you can only disable closed Betas. If a feature has dependencies that are in closed Beta, then you can't enable it. If you want to enable a closed Beta, [contact Support](https://support.okta.com). When you enable an open Beta, it triggers an email to the admin who performed the action.
```

2024-03-07 19:31 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md](https://github.com/okta/okta-developer-docs/blob/d33e3d16f6fc12e3dcebd1276ee843a2544b2fe8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Ffeature-lifecycle-management%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3625a2f2-face-486d-8678-b511184a2102) | 100  | 45  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.aff8d10f-e00b-4dab-8466-52e15d2407a3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-03-07 19:31 UTC, grahamsmith-okta approved these changes

2024-03-07 19:45 UTC, merged