Update to OIE overview page for PATEAM
okta/okta-developer-docs pull request #4780
Opened 2024-04-23 22:39 UTC by susanharper-okta

## Description:
- **What's changed?** Update to OIE overview page for PATEAM
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-704690](https://oktainc.atlassian.net/browse/OKTA-704690)

2024-04-23 22:39 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/d90be6f52febce6f490dbb1ccb3792b446fbfb6a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-overview%2Fmain%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c66d7eb9-7556-4616-acee-cdfc48b0060e) | 53  | 43  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.af5f856d-f284-43cd-901a-d97d15fd47cb?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-04-23 22:47 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/6797b5e066adcb0530dd64aaa9bc1124c76d3e39/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-overview%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3f5311c3-124b-41c7-adb3-88ac197a5143) | 51  | 69  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.056a9a23-cf8a-48ab-87f3-7ef624aff4cd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-04-30 19:58 UTC, susanharper-okta commented
approved by Dan in Slack

2024-04-30 20:06 UTC, grahamsmith-okta requested changes
just a few comments

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +Access the **OIE Upgrade Hub** in the Admin Console and review any outstanding tasks. If there are any remediation tasks required, those remediation guides appear in the **OIE Upgrade Hub**. If there
```suggestion
Access the **OIE Upgrade Hub** in the Admin Console and review any outstanding tasks. If there are any remediation tasks required, those remediation guides appear in the **OIE Upgrade Hub**. If there are no remediations required, then your upgrade is easier.
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +Keep in mind the following considerations:
```suggestion
Consider the following:
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +The rest of the upgrade process is defined in the next section. Which steps that you take are related to your deployment model. Okta has carefully considered how you can break up the upgrade steps to
```suggestion
The rest of the upgrade process is defined in the next section. The steps that you take are related to your deployment model. Okta has carefully considered how you can break up the upgrade steps to ensure that you maintain the best user experience across your applications.
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +The rest of the upgrade process is defined in the next section. Which steps that you take are related to your deployment model. Okta has carefully considered how you can break up the upgrade steps to
don't need which and that in the same sentence

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +    * **Self-service & Admin-initiated Password Recovery:** Make sure that users can recover their factors with no impact to the user experience.
```suggestion
    * **Self-service and admin-initiated password recovery:** Make sure that users can recover their factors with no impact to the user experience.
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +    * **New Account Activation:** Make sure that the account onboarding experience works as expected end-to-end to ensure that users have a smooth start.
```suggestion
    * **New account activation:** Make sure that the account onboarding experience works as expected end-to-end to ensure that users have a smooth start.
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +    * **Session Management:** If you’re using the Sessions API, some [methods for the Sessions API aren't supported in Identity Engine](https://support.okta.com/help/s/article/v1sessionssessionid-API
```suggestion
    * **Session management:** If you’re using the Sessions API, some [methods for the Sessions API aren't supported in Identity Engine](https://support.okta.com/help/s/article/v1sessionssessionid-API?language=en_US).
```

2024-04-30 20:06 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
> +    * **Session Management:** If you’re using the Sessions API, some [methods for the Sessions API aren't supported in Identity Engine](https://support.okta.com/help/s/article/v1sessionssessionid-API
I changed each of these to sentence case but if they're actual feature names I'm fine changing them back to capital.

2024-04-30 21:24 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/f4d4e67dec8ae9f91136d0c77b2c1aade9f96b75/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-overview%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7460fa58-464d-4fed-83b6-2a9c7b897121) | 51  | 69  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0532d24f-1ea6-4f97-8d1b-6cb932fe6723?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-04-30 21:50 UTC, grahamsmith-okta approved these changes

2024-04-30 21:50 UTC, merged