OKTA-727037 - Minor updates to OEL
okta/okta-developer-docs pull request #4916
Opened 2024-06-19 17:46 UTC by brianduffield-okta

## Description:
- **What's changed?** Adding a minor descriptor update and one example to OEL docs
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-727037](https://oktainc.atlassian.net/browse/OKTA-727037)

2024-06-19 17:46 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/a632ecf6b61f7083960ed0b1f8f61768459b9bf7/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/947167b1-8ad6-4940-9cca-efab01992dad) | 85  | 49  | 91  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.98b2221c-19d2-4abf-a5e2-8770a00854fa?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-22 20:11 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/0bcc44d012360a90f2f89221e03f73af0c6af4e0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5b66921d-36be-4487-8556-d29dc41335a4) | 85  | 49  | 91  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.cdbd0ddf-1514-4ce1-85d9-6339441a2223?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-22 20:22 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/bac5c07fdd08bdabbd9eb9ca3d0fedd80eeec6b6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b03f1514-c3a1-4620-8158-df8a7e7cbae1) | 89  | 51  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d89d7599-c23e-452b-a822-b9cbec7df439?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 18:54 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +This document details the features and syntax of the Okta Expression Language (EL). You can use this language throughout the Admin Console and API for the Okta Classic Engine and Okta Identity Engine
I don't see it on Confluence, but the style guide in the devdocs repo still says not to use articles.
```suggestion
This document details the features and syntax of the Okta Expression Language (EL). You can use this language throughout the Admin Console and API for Okta Classic Engine and Okta Identity Engine.
```

2024-07-23 18:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromWindowsToIso8601` | (String time)                      | String           | Windows timestamp time as a string (Windows/LDAP timestamp doc)
```suggestion
| `Time.fromWindowsToIso8601` | (String time)                      | String           | Windows timestamp time as a string (Windows/LDAP timestamp doc)                                                    | The time expressed in ISO 8601 format (specifically the RFC 3339 subset of the ISO standard) |
```

2024-07-23 18:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromUnixToIso8601`    | (String time)                      | String           | Unix timestamp time as a string (Unix timestamp reference)
```suggestion
| `Time.fromUnixToIso8601`    | (String time)                      | String           | Unix timestamp time as a string (Unix timestamp reference)                                                         | The time expressed in ISO 8601 format (specifically the RFC 3339 subset of the ISO standard) |
```

2024-07-23 18:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromStringToIso8601`  | (String time, String format)       | String           | Timestamp time in a human-readable yet machine-parseable arbitrary format (as defined by the [Joda time pattern
```suggestion
| `Time.fromStringToIso8601`  | (String time, String format)       | String           | Timestamp time in a human-readable yet machine-parseable arbitrary format (as defined by the [Joda time pattern](https://www.joda.org/joda-time/key_format.html)) | The time expressed in ISO 8601 format (specifically the RFC 3339 subset of the ISO standard) |
```

2024-07-23 18:55 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromIso8601ToWindows` | (String time)                      | String           | ISO 8601 timestamp time as a string
```suggestion
| `Time.fromIso8601ToWindows` | (String time)                      | String           | ISO 8601 timestamp time as a string                                                                                | The time expressed in Windows timestamp format                                              |
```

2024-07-23 18:56 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromIso8601ToUnix`    | (String time)                      | String           | ISO 8601 timestamp time as a string
```suggestion
| `Time.fromIso8601ToUnix`    | (String time)                      | String           | ISO 8601 timestamp time as a string                                                                                | The time expressed in Unix timestamp format                                                  |
```

2024-07-23 18:56 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +| `Time.fromIso8601ToString`  | (String time, String format)       | String           | ISO 8601 timestamp time converted to format using the same [Joda time pattern](https://www.joda.org/joda-time/k
```suggestion
| `Time.fromIso8601ToString`  | (String time, String format)       | String           | ISO 8601 timestamp time converted to format using the same [Joda time pattern](https://www.joda.org/joda-time/key_format.html) semantics as fromStringToIso8601     | The time expressed in Joda timestamp format                                                          |
```

2024-07-23 18:57 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
>  * Standard relational operators including <code>&lt;</code>, <code>&gt;</code>, <code>&lt;=</code>, and <code>&gt;=</code>.
```suggestion
* Standard relational operators including <code>&lt;</code>, <code>&gt;</code>, <code>&lt;=</code>, and <code>&gt;=</code>
```

2024-07-23 18:58 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
> +* The `matches` operator to evaluate a string against a regular expression (Regex). <ApiLifecycle access="deprecated" />
```suggestion
* The `matches` operator to evaluate a string against a regular expression (Regex)  <ApiLifecycle access="deprecated" />
```

2024-07-23 18:59 UTC, brentschaus-okta requested changes
Just a few nits

2024-07-23 19:15 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/821a4fd1cb4070dd7718c1a017c3ffe9e2c8eeb6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c01b2e89-3fb7-49a3-a8ff-86607282625f) | 89  | 51  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.731211a3-e855-4ee1-9b4d-e2d764b34cef?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:15 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/2fdaeb84bb7bc62a00e8ff7af0898bdb2b24193b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/57b13980-6b44-4ffb-a0d3-c22863c74179) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.40708bdb-eea7-4f35-aa2f-5e6e692200bb?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:15 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/b0784eaad080c140b4f3a92d4422d9e75d78bf7f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/507f67ab-bd2c-4661-bd80-1a5b798f4cea) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.73fd90ff-7a4e-4e50-b9b8-7f5974fd0b03?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:15 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/9e7ad3742aa4fbc12faa68d9f1b6c47b3bb78741/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f7e7b2c3-3060-452d-8b4f-83d5c687ff7a) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.2e54c758-922c-4d5e-8ea2-bd955fe39d97?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:16 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/465eddeab40ec7a5cfe18070dd455644ad6ef00d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f4b4175f-20ff-44b8-8c77-29005760ab23) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e38e14b8-93a8-40d4-bcf7-c1521ce97dc4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:16 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/c02dfd68274ce0e492366f9161e2684d24bae0c5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ea88c4f9-28e9-418e-9529-3a85387d4d24) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6f63d08d-cd24-47c1-945d-aea697d782af?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:16 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/dfa3c4fc75bc51cf3da0eccf12f83287c569efbc/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/372c8b54-840e-4f31-9ba0-ea20e51cc0f5) | 89  | 52  | 92  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.aabd3456-0169-4b38-ae3a-cf4cb679c163?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-07-23 19:19 UTC, brentschaus-okta approved these changes
LGTM!

2024-07-23 19:29 UTC, grahamsmith-okta approved these changes

2024-07-23 19:30 UTC, merged