factors deprecation
okta/okta-developer-docs pull request #5027
Opened 2024-08-20 20:17 UTC by susanharper-okta

## Description:
- **What's changed?** factors deprecation
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-794896](https://oktainc.atlassian.net/browse/OKTA-794896)

2024-08-20 20:18 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [75](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cc0d3c43-caca-423e-b649-43753806480e) | 52  | 84  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f231a0bc-22e9-483e-8a95-38c2a0b6b906) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9c05cf45-31c4-4d8c-9414-26b31ffffeb4) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5cc0df96-819f-42f0-888d-cfeb31321a92) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ccdecbc5-c76a-46a8-96df-6ce59950a7d8) | 100  | 74  | 59  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65f50409ca723db1a942637aee42a354b23375a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cbf57072-05d4-4d8e-a988-16150992d298) | 85  | 74  | 58  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.dce99234-406e-4f5d-ba66-c342a7106c5d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 21:02 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7caeb7a1-7626-4072-8ca6-6bc2ff91be50) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/120d1c1a-4b32-4a1d-8945-159bfe17c0d7) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8743991c-ac56-41d7-b3a2-e01dbd623c1a) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/150ba5ad-51da-43c9-9466-9b63d7981405) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/225c0692-32e1-4bf2-be68-c28c81eeba46) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/3274d183689b0790f918ce73c951336e045e4685/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f799a2d3-b1a1-4984-b461-aa3e5e6dad3f) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7ccf6a51-0d0a-48ea-aa83-1689a23331de?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 21:16 UTC, grahamsmith-okta requested changes
two questions

2024-08-20 21:16 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
> +With an upgrade to Identity Engine, after resetting all the factors, when the GET `/factors` API is then called, the forgot password question is returned as a factor in the response.
There are a lot of setup phrases here. Would it work to simplify to something like this?

After you upgrade to Identity Engine and reset all factors, calling the GET `/factors` API returns the forgot password question in the response.

2024-08-20 21:16 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md
> +The authentication flow for the Classic Engine Authentication SDK methods, and their backend API calls, function similarly to the Identity Engine SDK methods. Both versions call Okta, receive a trans
are the "authentication flow" and "their backend API calls" two parts of a compound subject? or is the authentication flow for the "methods and their backend API calls" ? If it's the latter, we should change it "functions"

Sorry, having a hard time parsing this sentence

2024-08-20 21:48 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3410dd39-db02-4331-bb08-7d33661ba1da) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c51e907a-c03b-4426-bb55-dc51f1e95042) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2d13a014-59b5-43b4-a7f9-8e9cc2d2cb8c) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/832ee63d-29dd-4b95-927d-79bde5ef913b) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2a25b387-8a9f-47dd-a79e-9157ee7d6f68) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/566c829884fea91a1828e5ea5aa153c1dcc5833d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9db5f26e-6d73-47b8-ba3b-cdc706629a9a) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e07ad4dd-b0fb-45fb-a3d8-fd6465ecc07a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 21:52 UTC, grahamsmith-okta submitted a review, later dismissed

2024-08-20 22:12 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6f2ef879-99a0-4f5e-9251-ff7c3b960299) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e8c16032-dbd0-438f-93b8-2edad34fac74) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d41cbda-0722-4ec2-b1c7-b11872c69448) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d1e60ab1-dd72-42bc-a39b-6d088b7065fd) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/06754f1c-ca01-481e-9e69-3e5937f77884) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/33cc16e4f9f21a68a1774adddac8d0ac9a9de880/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4e8ef616-502a-40fa-9fc7-fd69a272c8a8) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5b5eb5f3-e0fb-4318-b1d3-0969df8f9f60?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 23:09 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/22b4e56b-0411-4f27-bdcd-ffb8c2890a9a) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c87e91e-cf54-49b4-95ca-67a0630faadf) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/126acb21-2eea-47ef-96d6-17aa63e547d3) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d0bd7b6-4bbd-4652-a023-89da83882b38) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ff884208-b4a4-408e-9e87-196c1bd01752) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/032300a30a2d9fdb69ad7aefc832ee3cedb7f5fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/076ca828-f587-4c15-9b0f-20c57b098513) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d7ee07c6-009b-468d-a153-5c2501fd8057?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 23:26 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/489c5a4d-9adc-4f99-ad72-98f88bf5a837) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/86a9182f-5ca4-4f1f-a094-77fef7da0201) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/175f066a-1518-4786-90ac-86e868dfad80) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7ebb777a-164d-4f00-8c5e-1044fc0804ec) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cb6ded6f-b7bf-46e8-9893-703eb4708905) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/1b2d947adf67e2b3c60316c6efb04dccf1776d3f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8465d140-0d70-46fa-9e2b-b997b98749b9) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5b028303-0855-4365-8199-ecbf024320f6?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-20 23:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2d091f1a-aa25-4916-92fd-7d7e3db029bd) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/af0a4aa4-db84-45d1-8ef1-34a1e376413a) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ff07f9fb-0469-4056-9866-b9ba53e69d71) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0b9703cc-ca0d-4339-bfcc-8ff364c76ca4) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3e0484bc-2c8c-45de-962a-0190575016f9) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/65917d99b65b6379b05b07a474b58a381774274e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b6ff2dfb-a7b3-4ce2-ab7e-f9bb47eefed0) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9076cd47-77c6-4a2e-84d9-8339a2fb734e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-21 00:19 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2aeec7a4-edac-4d4f-90c3-019f0f2ae9df) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7cb687c6-44d7-46aa-9d7a-14b37095713b) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/efdec9ee-15e1-4cd4-b591-93d3016f969e) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a31a6578-06eb-46ec-b4d9-d7c526c77097) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/55e450bc-1e56-47b9-a3c8-bf279ec18e9b) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/13770a5b3fc5fa4f068d35a57bb22861b961f277/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5a36590b-d9fa-437e-8b03-6ab7a955b210) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.368c78f3-3078-479c-8e58-ab771c42098b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-21 15:59 UTC, grahamsmith-okta approved these changes

2024-08-21 16:12 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e68160b2-8be5-4995-96be-b9f33e8df0e5) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d332f16-724e-4528-9b7a-122713343ea5) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e1b3eec6-76e3-4d45-8275-86fa55d43d24) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d6b660cc-5929-491d-b051-ed5062e4e01d) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/685a8767-a64e-4807-9e62-fc5e902a830b) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/e4005362a5ae20707c48f9eda6e52adc20dcebbd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d6c001a0-ccbb-4afc-a721-9d0f5c521444) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ecfd3afe-e808-4a1d-9bd7-847fa2962d48?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-21 16:17 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5b96d566-f218-4333-8aa5-87139978030e) | 24  | 100  | 93  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fie-limitations%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/75430398-b8d0-483c-b97e-1717cbd82005) | 56  | 79  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/index.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8732d7b3-3f33-45e0-bdee-25ca5caf9bbb) | 81  | 100  | 81  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmfa%2Fmain%2Fsms%2Fenrollfactor.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4ffb2df2-182d-4d7b-963c-350f6b8d343b) | 100  | 100  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Faspnet%2Fauth-vs-oie.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/051d01d6-7ab6-4938-a253-67c2983498f3) | 100  | 100  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fios%2Fauth-vs-oie.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/352beda0-5df6-4e00-b542-185736224f97) | 100  | 74  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md](https://github.com/okta/okta-developer-docs/blob/538e65db20215b6674fa014bc1d0b63a9edaa234/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-api-sdk-to-oie-sdk%2Fmain%2Fnodejs%2Fauth-vs-oie.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/89f5850c-6f82-42b6-b8ff-9824c872c303) | 84  | 73  | 84  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.589ea588-1b23-4563-9119-dd17abd6c3a0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-08-21 16:41 UTC, grahamsmith-okta approved these changes

2024-08-21 16:41 UTC, merged