Sdh okta795373 OIDC dep
okta/okta-developer-docs pull request #5056
Opened 2024-09-06 17:34 UTC by susanharper-okta

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

2024-09-06 17:36 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/612fc90c-2930-47b2-881c-f13a515e74d0) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a1ec33a8-9864-4f3e-b049-68af41614ce4) | 43  | 92  | 57  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e4aa1b66-8aae-4521-96a1-e86478fd1881) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/89c259d8-494f-4655-a339-d58a675d7e74) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/da790ffe-8929-460d-bbdc-b525bf5ac538) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/63b5bacc-7cf7-40a2-9365-7963ca81bb97) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b1b4262-bf0c-4071-a170-1296a82c9e15) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6458be4a-569d-4532-90d4-308771103d12) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-auth-js%2Fmain%2Findex.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e69fabaa-3e05-4976-8e67-ba0de3b104b0) | 61  | 70  | 51  | 90  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/angular/guide.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-sign-in-to-spa-authjs%2Fmain%2Fangular%2Fguide.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/49a91b65-8cb5-4792-9c20-008269884de5) | 43  | 68  | 37  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/react/guide.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-sign-in-to-spa-authjs%2Fmain%2Freact%2Fguide.md) | [65](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0fe3bdc8-f8a2-4099-ae5f-88825d324f03) | 56  | 47  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/vue/guide.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-sign-in-to-spa-authjs%2Fmain%2Fvue%2Fguide.md) | [62](https://okta.acrolinx.cloud/api/v1/checking/scorecards/60e63845-5488-402f-9907-f7d870e0074b) | 42  | 77  | 41  | 87  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0f5996ec-c407-4cfa-bb18-8296ead144e1) | 64  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2f686c60-fcb1-4b85-b47d-7dd317015dbf) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e873cb07-5a8a-4d9d-a302-191698b8886d) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/4c2f4ae0b05a8fcb185cc0ed32aaca05761a85f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d0c58d94-107e-4d72-9e67-87542832213b) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secre [...]

2024-09-06 17:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e06f6073-6daa-4ef4-a437-7af89620931e) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/42231ee5-adfa-432c-8161-a89d22fca930) | 43  | 92  | 57  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3bb59735-2af2-4aa3-95f7-23368202ac83) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43ba0f57-d9be-4b88-9f11-8788bb415805) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4077d362-fe91-4e81-b3af-429ee2ccf11f) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0ad3a520-a8b1-40d2-83c7-f7294e663f1f) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2504b230-0bcf-4649-ac99-87ae7ecb4255) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e5b6b087-ba98-4c02-8a78-0abbb022d769) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b4eddc57-7ed9-40d3-9f98-a2f8325540a2) | 64  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ee7b02a6-4d68-441b-8500-5941c186dc17) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/40b7135d-160a-446d-90a2-f1e82612a604) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f43e499d-f073-4d19-8a34-7a89bbab136c) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fclient-secret-rotation-key%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e5b0b95d-7079-46cf-b15f-4eee7b79c367) | 79  | 74  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-access-policy%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/31c57c90-9dad-4fbc-8483-66c5f561ff4a) | 90  | 82  | 63  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-ciba%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/71c2d69b-ab79-45b6-bb0c-6f73fd5ec5f0) | 87  | 72  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170da05669022df6bd1459f7d9140893ec6503a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-native-sso%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/27090846-e993-4d9d-ad97-26871bffc07b) | 32  | 72  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md](https://github.com/okta/okta-developer-docs/blob/7170 [...]

2024-09-06 20:32 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5fe87f42-c445-4c4f-bd63-2d85a5102f8a) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/718c366c-130a-4237-8af7-247d693abe1f) | 43  | 92  | 57  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7ea17722-c1ef-41aa-92ec-66ab0260245d) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bdd83230-a00f-4b60-bb0b-e4090ac0c275) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a53b01ab-ef50-4ee1-868f-99c9b7df23c0) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bdbdbd2c-a2ee-47aa-b1fd-fe926dee934b) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/20d8f17b-d47e-4f0a-8fcf-ff8a19a94aec) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/577d8740-0d3e-4441-a6e9-ba8b297bcc56) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1c76ba3c-740d-4eb1-9ca0-aa399cfb7f19) | 64  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d8fb0a25-f93a-468d-8bec-f0c1f559e4bf) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f4d041eb-62df-4a23-be46-cc2aee34ce2c) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4dffd769-5208-404a-9ce1-159f1ec547ee) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fclient-secret-rotation-key%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/57b85912-fd55-42d5-9a85-3f1fe0263b10) | 79  | 74  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-access-policy%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6534bd23-8236-466a-9ae3-d1b5266360bf) | 90  | 82  | 63  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-ciba%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a518e581-0c34-411d-9bb2-83e8c9d7e2bb) | 87  | 72  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc672b2728df84c895470b51f4cbe04739611f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-native-sso%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ba38d0c3-216a-457e-b5c2-e9535c1030ea) | 32  | 72  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md](https://github.com/okta/okta-developer-docs/blob/6abc [...]

2024-09-10 15:02 UTC, grahamsmith-okta requested changes
Just a few edits

2024-09-11 16:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b184c6b7-0231-4d48-a10f-e83e647fbdd6) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/06393d46-5b37-42e5-b60f-00d0173af403) | 43  | 85  | 61  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/439b3890-b06b-46c9-aed5-68a464435389) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d604121a-d975-4b1f-a1d9-8dbb511f46fa) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b35084d9-c3ad-4c73-809f-b8032aa19712) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/aa77eb6d-32af-48ce-ac0e-2a5b24e03c46) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/064562da-58d7-468d-be7e-f28ba8a256a0) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2507e3b9-57a7-41dd-b500-4fcf6f0ab4ef) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dc157f5e-4d75-447d-badc-88e1b5df235b) | 61  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e4a78a9f-35b6-46a1-91b2-d28f31b2a848) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c1591a0-06eb-4abe-9884-20ed70d0cf23) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/eb5ec047-2df0-46fd-a186-e04d2f70799f) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fclient-secret-rotation-key%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b13559ca-60b9-456a-bf24-cd0cebe51f53) | 79  | 74  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-access-policy%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bb699556-8d75-4756-a4e0-2ee78c98b5d4) | 90  | 82  | 63  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-ciba%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/652920b3-a844-4111-a782-0f1aeb498b02) | 87  | 72  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191643346f6253eaf76ab1cbbdb3325ac9441ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-native-sso%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/48bca794-47cb-495c-8fbf-57d137397182) | 32  | 70  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md](https://github.com/okta/okta-developer-docs/blob/9191 [...]

2024-09-11 16:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b274eef5-9c95-4a70-8904-e15dbcd01f8b) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/75857ddc-98de-41e0-b421-df8468a6d658) | 43  | 85  | 61  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1a07629a-305e-4d7c-abd0-3ceaba0a56ef) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/93de765f-cd9c-46e3-9b8f-2d36d6f6a16e) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d3e4464-cb97-4209-9fa9-910f81d36d99) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a22e389f-a51f-40ac-abff-7a01bc954dfc) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/950f48b9-8c8d-4cde-a858-037972472360) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dc6d039b-dfc7-405e-aa9f-7f02b8ba8cf4) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/68f97d65-194d-40f8-8cf1-ae6bce171260) | 61  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e7b2b297-b11e-4b43-ac3e-cc1dcbdb017f) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c2848630-492f-48c1-a6e9-5247298f2407) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c5b68213-2549-4a4d-8a7f-379beac35372) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fclient-secret-rotation-key%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c3ad7246-8b06-4c9a-baa7-7425f7f13f05) | 79  | 74  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-access-policy%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/81ea3ae7-34f5-49d8-9438-f43a9a0355c6) | 90  | 82  | 63  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-ciba%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/12d93659-03e6-456d-8231-9bcfa05cbca7) | 87  | 72  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md](https://github.com/okta/okta-developer-docs/blob/64801d31645c4eacd9a8bd21e067bcef355c5200/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-native-sso%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cf704cc1-be9b-4b66-8f8a-b91408fc9b2e) | 32  | 70  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md](https://github.com/okta/okta-developer-docs/blob/6480 [...]

2024-09-11 17:02 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fapi-access-management%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c80c994a-6a03-4b98-af57-830c5765aefb) | 91  | 86  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Finteraction-code%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bf95d821-198a-4bc2-846a-d106e0b2cd32) | 43  | 85  | 61  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b40a1f3d-5e20-4795-b21e-8a7cde9d3793) | 100  | 60  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Foauth-openid%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f6adb4a2-749c-4e06-8cf8-03494e994bf2) | 43  | 74  | 97  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d1117da4-ab56-49aa-a804-b425971eb6f7) | 62  | 82  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9043762d-5cd3-47f3-a921-e1b24d98b875) | 55  | 55  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-logingov-idp%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d90f834a-a682-4f63-bae0-91d74679d853) | 65  | 65  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Fopenidconnect%2Fsettings.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/78a44eae-a02e-47d4-b219-fb894515269d) | 49  | 62  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauth-js%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/51609946-cd6c-464c-9d32-9c0a6efd6bdb) | 61  | 74  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6925938d-6e79-473f-b5ff-2815c539645b) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-self-signed-jwt%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a45ddde3-debc-4a7e-bcee-0b714fb4b681) | 100  | 88  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/22002b9c-4859-4661-ac30-ea1203978634) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fclient-secret-rotation-key%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3a369681-bf00-48b1-9e04-64f04ecc1f9a) | 79  | 74  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-access-policy%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1f9b66a2-a568-4fae-ab20-ed9169c848a4) | 90  | 82  | 63  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-ciba%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fedcec40-54aa-44b4-bddb-d2dd5bcc9c6b) | 87  | 72  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md](https://github.com/okta/okta-developer-docs/blob/931718a8f46a78674e1c21079944a9896c1e0155/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-native-sso%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6ed940f5-5119-4019-b626-22fcf1bb342b) | 32  | 70  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md](https://github.com/okta/okta-developer-docs/blob/9317 [...]

2024-09-11 17:43 UTC, grahamsmith-okta approved these changes

2024-09-11 17:46 UTC, merged