OKTA-476264 Adding SIW variable
okta/okta-developer-docs pull request #5085
Opened 2024-09-19 18:44 UTC by thomascavanagh-okta

## Description:
- **What's changed?** Added a variable which fetches the latest version of the Sign-in Widget. Added to places in docs which explicitly mention the latest version. 
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-476264](https://oktainc.atlassian.net/browse/OKTA-476264)

2024-09-19 18:44 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-embedded-siw%2Fmain%2Findex.md) | [60](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dabb381b-3320-47b6-b861-3bc31767703f) | 27  | 63  | 37  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fembedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/24441094-fee6-4e2c-b240-c819e66415e2) | 36  | 70  | 95  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Faspnet%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c3730d9d-cd4b-4225-ad20-83c7271a2af1) | 34  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fgo%2Fwidgetforyourapp.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3a866768-90f6-4d27-87b5-1a7b6a98ac37) | 31  | 76  | 100  | 76  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fjava%2Fwidgetforyourapp.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/193f5c88-d428-4832-a038-74c80cd709b3) | 51  | 100  | 81  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fnodejs%2Fwidgetforyourapp.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d15ac2ec-5e3b-4cd4-989a-eabe75435f02) | 40  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Faspnet%2Fsiw.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9a863676-59b9-4ff2-b8e2-d46538fdbe52) | 52  | 69  | 57  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Fnodeexpress%2Fsiw.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dd19edca-44cf-4976-b702-d50ede63693b) | 36  | 53  | 82  | 82  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Faspnet%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/50eb450f-309e-40b7-9d03-8381a49903c5) | 31  | 74  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fgo%2Fintegrationsteps.md) | [61](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ff2abb98-42ab-466a-acff-986aaedb6f90) | 28  | 56  | 79  | 79  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fjava%2Fintegrationsteps.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3ecebd2a-5ca5-464f-8887-8fa57da630a4) | 32  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fnodejs%2Fintegrationsteps.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cbe21e86-e6a1-4786-9ae0-6618d6acb275) | 30  | 72  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8b37674630b2366a6c5b006e880d969d4b566d2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3649657b-1dc7-496c-b0d2-04640323e315) | 48  | 73  | 92  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c92c9291-e760-4d2b-bf26-9d37ea33e031?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:26 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-embedded-siw%2Fmain%2Findex.md) | [60](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fa350086-dab2-4abe-9d71-45009fdd2ff7) | 27  | 63  | 37  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fembedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a5e054ee-980c-422d-954b-079abd8e7e2f) | 35  | 70  | 95  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Faspnet%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a3643644-ae9f-4c76-aacd-fdd79e07f54c) | 34  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fgo%2Fwidgetforyourapp.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/415bae9a-b1c9-4d34-a991-1d5d55f471bf) | 31  | 76  | 100  | 76  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fjava%2Fwidgetforyourapp.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/08554c2b-5b1c-4406-a9dd-9b582c041509) | 51  | 100  | 81  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fnodejs%2Fwidgetforyourapp.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cd72eaff-eb4d-46cd-a198-c8961aec7e0d) | 40  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Faspnet%2Fsiw.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/02ce0398-c378-45a0-adbd-bdb34b2bd0f5) | 52  | 69  | 57  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Fnodeexpress%2Fsiw.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/62243ea4-f74a-41b8-bb94-14cb724b149e) | 36  | 53  | 82  | 82  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Faspnet%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/098075c1-e730-4439-aa2e-e78ba94cd842) | 32  | 74  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fgo%2Fintegrationsteps.md) | [61](https://okta.acrolinx.cloud/api/v1/checking/scorecards/aedad2a1-568d-49c7-b9cb-0d448a6c82a2) | 28  | 56  | 79  | 79  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fjava%2Fintegrationsteps.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e90f6d8e-1e3b-40ee-87da-c3499e4f4d63) | 32  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fnodejs%2Fintegrationsteps.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/71870cdc-b094-462c-a5b1-db9db206045b) | 30  | 72  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/214e3d994b42c06c568ef217db37250b3500f57b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/056ce41c-af8a-464a-88aa-3feb6fba4ab9) | 48  | 89  | 92  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e10ecf32-8c97-4d57-ae9e-3c1c4ac1ea8a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 17:11 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-embedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/110d3777-d357-4fbd-8f1a-3d61a6d4e80d) | 31  | 84  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fembedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f7503ff2-5852-4708-87cf-085a480dff5c) | 35  | 70  | 95  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Faspnet%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4e9854b3-96e4-4fdd-833f-0b76038d1d2e) | 34  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fgo%2Fwidgetforyourapp.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/653589c0-ad89-47f4-9901-deb7739f0bbb) | 31  | 76  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fjava%2Fwidgetforyourapp.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1e733d1d-84cf-4689-8693-0416d5d93b0f) | 51  | 100  | 81  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fnodejs%2Fwidgetforyourapp.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2abe447e-9da1-4c0f-b042-c0384a754935) | 40  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Faspnet%2Fsiw.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94a7adb8-6d98-4a40-bc05-53deff1c495c) | 52  | 69  | 57  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Fnodeexpress%2Fsiw.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8037475a-7c65-4900-bf4e-3048e2d3f1f7) | 35  | 81  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Faspnet%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fe17f26f-162e-4dda-a862-8a56b51d6047) | 32  | 74  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fgo%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f94c3d87-36cf-4167-8680-aa8c6e8bec78) | 28  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fjava%2Fintegrationsteps.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/610db796-2e17-4de7-8fee-dbfc975f3eb1) | 32  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fnodejs%2Fintegrationsteps.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2761a885-7641-49f1-9eb6-996a4a10110b) | 30  | 72  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/f3967341183795307ccd5e648ff2376dfb595192/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b967dd35-e098-47c0-b02f-f22d85739bb2) | 48  | 73  | 92  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.86b96768-53f0-4dc9-bc60-f3aee44c350a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 17:25 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-embedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b356d54-8dc5-4648-bd10-0e57a5df0574) | 31  | 84  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fembedded-siw%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/645ae304-7428-448f-91c6-f2484e055998) | 35  | 70  | 95  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Faspnet%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7a10706e-30d8-4226-ac0b-13cc96030baf) | 34  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fgo%2Fwidgetforyourapp.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/015059fe-331a-4d01-a560-42cbae62de3f) | 31  | 76  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fjava%2Fwidgetforyourapp.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/85e92965-5240-4033-ab07-f136d3c19b77) | 51  | 100  | 81  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fnodejs%2Fwidgetforyourapp.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d62023e0-d371-45e1-8b45-e999c73be4a5) | 40  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Faspnet%2Fsiw.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3c68ca08-6042-4639-a1bd-d15f41b6a167) | 52  | 68  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Fnodeexpress%2Fsiw.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c73b9618-4b53-4d84-a06a-722223093491) | 35  | 81  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Faspnet%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8d62cffb-16a4-44ed-bc8e-095e0763cf12) | 32  | 74  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fgo%2Fintegrationsteps.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f1c777d7-4f1c-49fa-90fa-bb4e923d3014) | 28  | 79  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fjava%2Fintegrationsteps.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/520e5a3b-0e2b-4f86-9f26-7a8629b69489) | 32  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fnodejs%2Fintegrationsteps.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6f089c2d-c5c8-46a8-916d-e1b9e8236198) | 30  | 72  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/b9fcafdd7483da1d8e162636e7d4456e57b209ef/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/10b924f8-9905-4ff3-af63-b35d3519fd12) | 48  | 73  | 92  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9b2a7eee-0d49-4d6b-a6a9-5f6eda55b0e9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 19:24 UTC, brentschaus-okta commented on packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
> +The Okta Sign-In Widget is a JavaScript library that gives you a fully featured and customizable login experience. The Widget can be used to authenticate users on any website.
If you're using "the widget", you don't need to capitalize the term.
```suggestion
The Okta Sign-In Widget is a JavaScript library that gives you a fully featured and customizable login experience. The widget can be used to authenticate users on any website.
```

2024-09-26 19:24 UTC, brentschaus-okta requested changes
Changes requested.

2024-09-27 15:55 UTC, brentschaus-okta submitted a review, later dismissed
LGTM

2024-09-27 15:58 UTC, grahamsmith-okta approved these changes

2024-09-27 17:09 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-embedded-siw%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/54dcf043-8d40-4b7d-85af-e2724023ab22) | 49  | 84  | 91  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fembedded-siw%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a8cdc68e-11bd-40fe-9308-43184d7f465f) | 53  | 73  | 95  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Faspnet%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a892e6ac-d7ad-4e1f-8af8-e420dc3f41cf) | 55  | 79  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fgo%2Fwidgetforyourapp.md) | [90](https://okta.acrolinx.cloud/api/v1/checking/scorecards/97945844-70f5-45e6-ab0c-3008f0207817) | 77  | 77  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fjava%2Fwidgetforyourapp.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/41fe4ee3-6c8b-4bb1-a06f-1aa2fd1d8173) | 81  | 100  | 81  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-common-download-setup-app%2Fmain%2Fnodejs%2Fwidgetforyourapp.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0f8e7586-756d-4214-92ae-e8abc60e4bdb) | 63  | 100  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Faspnet%2Fsiw.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94f025ae-14c8-48fa-a440-cd77bb9169fe) | 68  | 68  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-sdk-use-case-custom-pwd-recovery-mfa%2Fmain%2Fnodeexpress%2Fsiw.md) | [90](https://okta.acrolinx.cloud/api/v1/checking/scorecards/603b9304-950a-4962-a0e0-9a913caf406d) | 53  | 82  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Faspnet%2Fintegrationsteps.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1036f6f7-6b39-4014-a587-4ff472d91779) | 74  | 74  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fgo%2Fintegrationsteps.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/71549f9a-93f0-40af-b691-0e6982249a53) | 66  | 80  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fjava%2Fintegrationsteps.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/42f477c4-17e4-4444-a05a-f4245bc97185) | 70  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-embedded-widget-use-case-load%2Fmain%2Fnodejs%2Fintegrationsteps.md) | [92](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5c867a02-e50c-4ff8-a332-0e0244b4bb99) | 73  | 73  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/a0b8902c9ca4e5f8772b4d8b79e38af1b69ce8bd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/500c8158-b2c6-4892-93e8-e2eabeeefbe8) | 65  | 73  | 92  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fff9095a-48f8-425d-8185-926aa307a499?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-27 17:26 UTC, grahamsmith-okta approved these changes

2024-09-27 17:28 UTC, merged