OKTA-809423 - Create system log query guide
okta/okta-developer-docs pull request #5099
Opened 2024-09-25 14:59 UTC by brianduffield-okta

## Description:
- **What's changed?** As part of the THI API migration process, moving a significant amount of existing instructional text from the VuePress [System Log API](https://developer.okta.com/docs/reference/api/system-log/) to a new guide that will appear in the reference section. 
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-809423](https://oktainc.atlassian.net/browse/OKTA-809423)

2024-09-25 14:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/d59e9724488478ffe93136b2425978a688af6958/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/07626f0d-45cf-4d56-8233-fe3b9703325b) | 78  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c9648648-b4cc-4404-b983-bab9f5ed2d98?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-25 16:53 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/8df95612aff21b3adff007773ad13153d70ce429/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/256413c8-77c6-4f52-a0bd-a19f79bdc488) | 76  | 57  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f791aac4-f443-4c72-bd58-95fcb921b50a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-25 17:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/1701497e7288cf99448280448b2a14c7d07fd835/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6f2ceeeb-538b-48a1-9a25-5393b72a5191) | 76  | 57  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.57dcc0b1-9318-4a37-8a45-e40bf850d920?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-25 22:52 UTC, susanharper-okta reviewed
some edits

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | WcKPxq1f8QLfFvv3UPHhhgAACGM   | ed317758-8776-4240-a540-277c44dcb408   | application.lifecycle.update                  | Update application                    |
```suggestion
|                             | WcKPxq1f8QLfFvv3UPHhhgAACGM   | ed317758-8776-4240-a540-277c44dcb408   | application.lifecycle.update                  | Update app                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +| trs5JnlvlaIQTOqOj9imLy7lA   | WcKPxq1f8QLfFvv3UPHhhgAACGM   | f24790d0-d324-47f8-aac5-c27a31ab928d   | user.session.access_admin_app                 | User accessing Okta administrator app |
```suggestion
| trs5JnlvlaIQTOqOj9imLy7lA   | WcKPxq1f8QLfFvv3UPHhhgAACGM   | f24790d0-d324-47f8-aac5-c27a31ab928d   | user.session.access_admin_app                 | User accessing Okta Admin Console app |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             |                               | 421c1551-71b2-4ebe-a70d-b5f7d3698429   | application.lifecycle.update                  | Update application                    |
```suggestion
|                             |                               | 421c1551-71b2-4ebe-a70d-b5f7d3698429   | application.lifecycle.update                  | Update app                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             |                               | 06a50bbe-44fd-40de-83e6-2e4cc2a17d16   | application.lifecycle.update                  | Update application                    |
```suggestion
|                             |                               | 06a50bbe-44fd-40de-83e6-2e4cc2a17d16   | application.lifecycle.update                  | Update app                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +| trsUz2TG3wKS6ar1lvWzHo71w   | Wij-6q4YuniRd9yTmWHpfwAAADc   | 3e240ff4-6af7-47f2-b107-a2ef661ffc01   | application.user_membership.change_username   | Change users application username     |
```suggestion
| trsUz2TG3wKS6ar1lvWzHo71w   | Wij-6q4YuniRd9yTmWHpfwAAADc   | 3e240ff4-6af7-47f2-b107-a2ef661ffc01   | application.user_membership.change_username   | Change user's app username     |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             |                               | 572b05e9-b6be-4dfe-8bc3-01bb3a5a1af5   | application.user_membership.add               | Add user to application membership    |
```suggestion
|                             |                               | 572b05e9-b6be-4dfe-8bc3-01bb3a5a1af5   | application.user_membership.add               | Add user to app membership    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             |                               | 30f29bbf-3218-429b-827a-0a93809591db   | application.user_membership.remove            | Remove users application membership   |
```suggestion
|                             |                               | 30f29bbf-3218-429b-827a-0a93809591db   | application.user_membership.remove            | Remove users app membership   |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | Wij-964YuniRd9yTmWHu1AAAAEA   | 5f98d062-05a9-4ede-89a0-8a2ce27efdd4   | user.session.access_admin_app                 | User accessing Okta administrator app |
```suggestion
|                             | Wij-964YuniRd9yTmWHu1AAAAEA   | 5f98d062-05a9-4ede-89a0-8a2ce27efdd4   | user.session.access_admin_app                 | User accessing Okta Admin Console app |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | Wij-95eCbHF7In2MKNavlgAAD9I   | 45f71ac2-e8b2-4c19-b4cc-d2560108c889   | application.lifecycle.update                  | Update application                    |
```suggestion
|                             | Wij-95eCbHF7In2MKNavlgAAD9I   | 45f71ac2-e8b2-4c19-b4cc-d2560108c889   | application.lifecycle.update                  | Update app                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             |                               | 46b85d65-01c6-44d2-86d2-25704804b1c5   | application.lifecycle.update                  | Update application                    |
```suggestion
|                             |                               | 46b85d65-01c6-44d2-86d2-25704804b1c5   | application.lifecycle.update                  | Update app                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +| 102GALFw8CzRT2KXoqnca8Jdg   | Wij-AJeCbHF7In2MKNaOpAAAEC4   | b9ab9263-a4ae-4780-9981-377ec8f2da86   | user.session.start                            | User login to Okta                    |
```suggestion
| 102GALFw8CzRT2KXoqnca8Jdg   | Wij-AJeCbHF7In2MKNaOpAAAEC4   | b9ab9263-a4ae-4780-9981-377ec8f2da86   | user.session.start                            | User signs in to Okta                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | Wij-7q4YuniRd9yTmWHrBQAAAKQ   | ff325685-0220-484c-82cf-5f8dc596acbe   | user.authentication.sso                       | User single sign on to the app            |
```suggestion
|                             | Wij-7q4YuniRd9yTmWHrBQAAAKQ   | ff325685-0220-484c-82cf-5f8dc596acbe   | user.authentication.sso                       | User SSOs to the app            |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | Wij-764YuniRd9yTmWHrkAAAAGw   | 232774ba-8feb-4b00-a732-e0ec99a24434   | user.session.start                            | User login to Okta                    |
```suggestion
|                             | Wij-764YuniRd9yTmWHrkAAAAGw   | 232774ba-8feb-4b00-a732-e0ec99a24434   | user.session.start                            | User signs in to Okta                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +| trswPONv4wIRaKDNWVVcmtceg   | Wij-6K4YuniRd9yTmWHo9wAAAAY   | d31d819a-1427-45b0-a8b4-8a8fb40c72f1   | user.session.start                            | User login to Okta                    |
```suggestion
| trswPONv4wIRaKDNWVVcmtceg   | Wij-6K4YuniRd9yTmWHo9wAAAAY   | d31d819a-1427-45b0-a8b4-8a8fb40c72f1   | user.session.start                            | User sign in to Okta                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +|                             | Wij-2q4YuniRd9yTmWHjRAAAADA   | 92606da8-7eeb-4ad7-8ffb-502dd0ec64cc   | user.authentication.sso                       | User single sign on to the app            |
```suggestion
|                             | Wij-2q4YuniRd9yTmWHjRAAAADA   | 92606da8-7eeb-4ad7-8ffb-502dd0ec64cc   | user.authentication.sso                       | User SSOs to the app            |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +| *null*                      | Wm@-R2s5lEMbNIB03krtvAAACyo   | 566671be-ec0b-400d-ad2e-6fc73ed12fb1   | user.session.start                            | User login to Okta                    |
```suggestion
| *null*                      | Wm@-R2s5lEMbNIB03krtvAAACyo   | 566671be-ec0b-400d-ad2e-6fc73ed12fb1   | user.session.start                            | User signs in to Okta                    |
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* `until` must be unspecified.
```suggestion
* `until` is unspecified.
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* `until` must be specified
```suggestion
* `until` is specified
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +An expression filter is useful for performing structured queries where constraints on the response object's attribute values can be explicitly targeted.
```suggestion
An expression filter is useful for performing structured queries where you can explicitly target constraints on the response object's attribute values.
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* Events that are published for a target user and application
```suggestion
* Events that are published for a target user and app
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* App SSO events for a target user and application
```suggestion
* App SSO events for a target user and app
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +The query parameter `q` can be used to perform keyword matching against a response object's attribute values. All supplied keywords must be matched exactly.
```suggestion
You can use the query parameter `q` to perform keyword matching against a response object's attribute values. All supplied keywords must be matched exactly.
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +> **Note:** When hyphens are present in an event instance's attribute value, they’re split and added to the list of matching candidates, in addition to the full hyphenated value. Therefore, events th
```suggestion
> **Note:** When hyphens are present in an event instance's attribute value, they’re split and added to the list of matching candidates, in addition to the fully hyphenated value. Therefore, events that contain the text `XOxBw-2JIRnCFd0gG0GjHAAABjY` are matched with a `q` value of `XOxBw`, `2JIRnCFd0gG0GjHAAABjY`, or `XOxBw-2JIRnCFd0gG0GjHAAABjY`.
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +The System Log response objects can be filtered by the response object's [published](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/SystemLog/#tag/SystemLog/operation/list
```suggestion
You can filter the System Log response objects by the response object's [published](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/SystemLog/#tag/SystemLog/operation/listLogEvents!c=200&path=published&t=response) attribute value with the following combination of parameters:
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +A free-form query that is too long returns the following error message:
```suggestion
A free-form query that's too long returns the following error message:
```

2024-09-25 22:52 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +The System Log API can be used to troubleshoot user problems. For example, you can use the following `curl` command to see events from user "Jane Doe":
```suggestion
Use the System Log API to troubleshoot user problems. For example, you can use the following `curl` command to see events from user "Jane Doe":
```

2024-09-26 13:44 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/a3fce3d55083ce0e04582a69ca776833b7e8160e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43a3ddc6-1990-4b8e-a73d-430e0d253348) | 76  | 57  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ac9b5082-a718-46c6-ae3c-e9670fdcb49d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:45 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/77bf69d8db17ededbbb3ce2b1d526fe29d5996f0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/442b7cf5-2332-4089-baea-48a570ddf440) | 76  | 57  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a3b7c18d-007e-41b1-92c5-64e34653e2d3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:45 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/8460b665b9a733087d7a6857cf3c2fbed2c2d512/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f0d8e1d3-acd6-4ad7-881d-9ac7d7204215) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6442a837-8086-4798-a7df-8172305501e4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:45 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/a555203fa089d06bcfd62529a1ef6434e34bc236/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e8e28246-b87b-4cf1-a1e6-47aa9d561ade) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.51f237cb-e8e4-4360-9410-7bce44097c1c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:46 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/08d2667ec62e5fcc69cb989d74836a44586f6eeb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0d93b955-a64d-4f44-8f92-83e65c12b472) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3890e6ca-6805-4d49-9425-94eb0294e3dc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:46 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/ab16c04208dcd710b4d554dd97277da562ce196b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/41d95201-862a-40ca-80e3-de30c52310c6) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.657a1e9b-b532-4b8d-864d-1d2fa8a4c908?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:46 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/3ff29989afbf67e9bffb37805379fb14800a30d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3293d92a-0544-41e6-90a0-aec79b8e3443) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.475a5334-5505-4100-ab67-ce5dfd52159a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:47 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/9bfba8ec9dc2ca249a0e4f3166c607c3e4201e9b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6067f843-6bc2-4ccb-a95f-9cd7e852f161) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3193eef6-424f-4e22-a771-8a62c22b56b3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:47 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/63484cb2ab6696b1670d6a125e0421356e0a56b2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dafed53d-f54a-4d59-87a8-2c734acac6b7) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bab4baa9-1baa-4caa-b057-656ffedf8c35?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:48 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/f97c666daeb6d8c75cfd0757acc45a310d431241/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c33c6c28-13b8-4387-9bf2-986924c58534) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3117f7de-4ab5-45a6-9f41-5ebca042cfde?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:48 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/43e3cfda66bcf4aba74ab888b0dea16749a444f6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7675c319-b988-4f65-a3d7-d303f15a52a1) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f29016a6-95b8-4285-a19a-231f2257ccd0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/2e2630cf597f9ef80d32159e6fa3dab32b6552ed/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2594f3d4-bebd-435f-82f0-1b89c5466454) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6971bec6-cdaf-4339-b48b-eb59bb20c552?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/e5cad90008d43b25cbd3d830c8552ec9c4f6711c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fefc0f89-8c70-410f-80b0-49b0edf11702) | 76  | 56  | 85  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.15158fb1-ee99-4f9a-8f33-e24219b9d08f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/27d6db09015d9e0547ebe068f109fbf53d6751e1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/abd10449-c2a8-4015-8d38-a30fd5b06042) | 76  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f565284f-35f6-47e4-83c0-1eae3a0599b9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/0cede6736ad730fa209dee12bbe3800baa355c96/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fbe93262-59d7-41fd-8577-ff9e4d30cbc1) | 76  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.200a1280-c4c8-4999-9f7a-6e7ed1748467?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/649ef2c2fe2f27fc039a5e1cb533cac77379362b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dfdd514a-6039-4857-b99e-60e048380a03) | 76  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7b2e9f9b-3e2a-4937-a59d-c7601597be72?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:50 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/2bd3bef2fd747339f832d94ae8e2f27f23258e48/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e6fe87a7-743b-41d9-bf76-3d57406bad00) | 76  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.11a5cad6-212b-42b4-a495-19b623c9736a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:51 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/c852675a5da086ec477042174b1a688cac93a734/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b8e866eb-cbe0-4e42-bfa2-7e01aa1dd365) | 76  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b1f0587c-8e90-449a-aa24-a37e300db9bf?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:51 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/6a7f0c0ff9a256c7e76b3d4654d09a870f0de5a1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7050e1a2-6f62-45c4-9e5b-39322145a528) | 74  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6477e083-fd5b-483f-a2fe-c5828a971b44?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:51 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/f665b1ba2fa295ca681a94cde4b86eed3e204a29/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9f701774-fb98-4776-80fc-87b0b0a0eefa) | 74  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.dc324e5b-5534-47a4-b960-c751c08d06f8?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:52 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/ac5018dc5593dd585d7fe4ed2dca3c56d7bad78c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6ee06623-42fe-48e2-b1ec-1c5c929ae4a0) | 74  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8706e6dc-0b2e-4fb1-8816-0d6027affb8b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:53 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/a39194d74ce8ddc4363bd69113082c555389a657/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/12ea47cb-a0ed-4ab6-8b05-2e5c63e52f39) | 74  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.743adf95-69e8-477f-b2a9-b05b604e2ce4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:53 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/9a8fe4cf8a7ae095ec9e03c8b292504d20b7fcea/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/71a01991-2e06-4c6d-8f09-b0a44547d329) | 74  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0992e8d8-9e85-4293-9e4f-39d2989765d0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:55 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/488b5fb79dab2f2ba23a0aec931c25c222d5e706/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a894bf9a-b290-404f-9aab-cd815170b8a4) | 72  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.10c3feaa-1982-4ae7-881e-7d40d73ef2f5?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:56 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/bef4fed2955ca218a8bfef36da58c115c83976dd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6bef92b1-a387-4b25-8441-603fa82c18f4) | 72  | 56  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ca94079f-22bb-47ea-99f1-2ded81b187c6?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:56 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/05350768882b9a98bd87076aa2f5b6983cab9efe/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/81ab14f1-4536-4049-9a3b-e2aa67ce2137) | 72  | 57  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.251446c7-c4e1-4b35-862b-c842d9cc8379?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:56 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/dca179505ff8181238bcb3cd00f0a0dd3138507c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e0aedb73-f5e0-41cb-852e-11a1eb1a5578) | 72  | 58  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.4399ebdb-0ef1-4789-acd9-881a71865add?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:57 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/fe45358c9e2ccc9fa52574e81e322367cf2ff594/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/79e91afe-33d8-499b-9a6a-04549dbdd176) | 72  | 59  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5b0cfaf9-bdf3-4790-9da6-f6f7ae2bda3d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:57 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/fa614e70fa8328b61e7db2e35d4a6db1fb9c340d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/140f205d-a589-47ba-88ad-3a51c03dd24e) | 72  | 60  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.984904eb-115d-46aa-85b0-9ea4566ce322?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:57 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/50cefa56095fdc2bd891d032404a4d38ed8757a8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ddc0bd6a-0117-48a9-a4f2-5feb4bef0a2f) | 72  | 61  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9f75da69-54f3-447a-a466-dd5571203e22?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:58 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/4b8ab9c889fcce7379290bba9ab9e6c44d0c2f56/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8efebcfe-50af-458b-a921-ed653dc2afd3) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.82155597-336a-4e36-8efb-f43218a603c8?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:58 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/7847bdca33d7c8ac2af690e65619f22a897297dc/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b1ca62cf-fd38-48a4-ac74-83ffe44af34d) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.36bc2a9a-21e9-4099-91cd-f167574600bc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/6fa1a39996d0fc0bbcececaf0e7e3c241f3e1aec/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b891e4fc-77eb-458d-8c58-fbf59a12615f) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.446f4faa-e06e-4603-a41f-0c0b3fdc0636?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 13:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/8e3b041ffa18c512442a418637bca7e2986869fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8a6b67bb-ddb6-464b-9fab-52b3e72d3323) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.30fdaf5c-0d63-4afb-9904-be716c9f3f4f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:00 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/e60da73fb12fb339edd849a153b0f696eead396a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c4d0ac65-bf2f-4132-a632-ad260107fe5f) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f479a527-03e2-45a1-9939-ed163ec8478d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:00 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/d808cb5faf45d2ea2c3475b51ecefaa309fe0242/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c28f582b-b68e-404b-be1e-0a8d6d810499) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fb28b7f3-138f-429a-a1aa-f876b5362ee4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:01 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/d13467128951b3ce73e29ce49457b868c44fca8e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3d713eb6-4230-4e5c-9a3a-e3c1b6edb1e5) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7a10df3d-c112-4755-9e2e-4d34435cb3e7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:01 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/b358bea9a60a1069eafe8689c872d2f581ab5025/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f31cb145-5a21-4b1e-81be-e2d7c3ed6472) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0597aade-2aee-43ab-85b7-9bf824f5f791?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:02 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/2316561c660cecf140665fcbaed174dbd99962e1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a51914fa-a608-42e2-acb7-a94973bedf38) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.052bac72-db64-4438-b5e1-c105e42bd7a5?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 14:02 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/12aeb655afa3d09c8d0c82807c7a4d457d559a0e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d2e815d9-2de8-4541-a78b-26a4dc0e9002) | 72  | 63  | 88  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.15811e67-7b66-4755-a307-595fdbf994ca?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-26 15:48 UTC, susanharper-okta submitted a review, later dismissed
LGTM

2024-09-27 14:16 UTC, dandennhardt-okta requested changes

2024-09-27 14:16 UTC, dandennhardt-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +  - `authenticationContext.externalSessionId`: Identifies events that occurred in the same user session
Let's change this from two to three identifiers and add 

`authenticationContext.rootSessionId`: Identifies events from all sessions that share a common root session. Some actions that can be attributed to a user, such as those taken by an Okta system actor on behalf of a user may have a different `externalSessionId` value. The `rootSessionId` field allows all of those to be identified and grouped together.

2024-09-27 14:16 UTC, dandennhardt-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* The returned events are time filtered by their internal "persistence time" to avoid skipping records due to system delays (unlike [Bounded Requests](#bounded-requests)).
Update for clarity:
The returned events are ordered by the internal "persistence time" which reflects when an event is actually committed to the log, and not necessarily the timestamp when the event occurred. The persistence time may differ from the externally available `published` timestamp.

2024-09-27 14:16 UTC, dandennhardt-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* The returned events are time filtered by their associated `published` field (unlike [Polling Requests](#polling-requests)).
Updated to say "ordered and filtered"

2024-09-27 14:16 UTC, dandennhardt-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +filter=eventType eq "app.auth.sso" and target.id eq "00uxc78lMKUMVIHLTAXY" and target.id eq "0oabe82gnXOFVCDUMVAK"
update to `user.authentication.sso` as `app.auth.sso` is not a valid event type

2024-09-27 14:42 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/67d07a27a8585a94e1ee872969f768bb01ad6179/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/da1b2344-c3b3-4d9a-8095-d1cf5c75cee1) | 70  | 65  | 75  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.15c46bc2-4904-4035-bd55-640c497ddc03?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-27 16:07 UTC, susanharper-okta reviewed
two nits

2024-09-27 16:07 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* `transaction.id`: Identifies events that have occurred together as part of an operation (for example, a request to Okta's servers)
```suggestion
* `transaction.id`: Identifies events that have occurred together as part of an operation (for example, a request to the Okta servers)
```

2024-09-27 16:07 UTC, susanharper-okta commented on packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
> +* `authenticationContext.rootSessionId`: Identifies events from all sessions that share a common root session. Some actions that can be attributed to a user, such as those taken by an Okta system act
```suggestion
* `authenticationContext.rootSessionId`: Identifies events from all sessions that share a common root session. Some actions that can be attributed to a user, such as those taken by an Okta system actor on behalf of a user, may have a different `externalSessionId` value. The `rootSessionId` field allows all of those to be identified and grouped together.
```

2024-09-27 16:42 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/a8954da6375622109540e74599b46ef183218f25/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ba770d15-e643-492f-b13b-37b7a0195d41) | 72  | 65  | 75  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5a2612ad-0b0b-4a83-af6a-a40a40da12fe?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-27 16:42 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/system-log-query/index.md](https://github.com/okta/okta-developer-docs/blob/a0c2a5420a9f1ef79c4460c5f80c768962fd2330/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fsystem-log-query%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4b2981f2-c368-468a-9921-1a70a2004fc2) | 72  | 65  | 75  | 98  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0a7809c8-ad8f-43d7-81ef-4cf6bf3bb1fc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-09-27 16:46 UTC, susanharper-okta approved these changes
LGTM

2024-09-27 17:01 UTC, merged