Keep me signed in (KMSI) API guide
okta/okta-developer-docs pull request #5124
Opened 2024-10-03 17:29 UTC by brentschaus-okta

## Description:
- **What's changed?** Adds a KMSI API guide.
- **Is this PR related to a Monolith release?** No.

### Resolves:

* [OKTA-795803](https://oktainc.atlassian.net/browse/OKTA-795803)

2024-10-03 17:53 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/9eb8393ab3d1f915c6ff03ba310ecd0f0670ef02/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/78812b5f-addc-4795-b65f-b99c993017d1) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/9eb8393ab3d1f915c6ff03ba310ecd0f0670ef02/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/047a3332-3999-4721-a919-39d270c659f2) | 85  | 79  | 69  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.80164515-5d59-48e9-b86d-99d575f378fa?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-10-03 18:12 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/ba2711ff579ea5b4243772e99191a32f842296a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bb761a30-ba52-4c61-a445-9ca6d70f443b) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/ba2711ff579ea5b4243772e99191a32f842296a3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0bea1b44-c148-4e2e-9385-0f198931a655) | 85  | 79  | 69  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6c8c07f3-dc39-4fbc-913e-2d5a513c2c05?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-10-03 18:42 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/695f8af4c71605173115cc3d72bbeedf69b72e1d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f0c0d830-d435-4a28-84fd-16d3132a4cb9) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/695f8af4c71605173115cc3d72bbeedf69b72e1d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1473ea84-13c2-4b31-a0b4-c8075bc3867c) | 85  | 79  | 69  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.745d25bd-dc31-401e-95c6-590d49e3e910?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-10-03 18:49 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/6b8534f67d3fd765c44ee54a83c49c7437ca8c9a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ff5eda69-5d93-4b23-978d-fe0ac5c00117) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/6b8534f67d3fd765c44ee54a83c49c7437ca8c9a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8a60440d-299b-488a-8ae5-ebd2160be443) | 85  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/6b8534f67d3fd765c44ee54a83c49c7437ca8c9a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d769760b-ac12-4c47-b603-579b9e4008f2) | 50  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a0511f3e-281a-419b-892f-b3468e817fb3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-10-03 20:59 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/4279b0329e1ea590c2dfde74f697b9f887152e0e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/096ba460-438b-4ec9-bae8-9570ead7caa3) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/4279b0329e1ea590c2dfde74f697b9f887152e0e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-keep-me-signed-in%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7b5fb720-e9b1-4167-95cd-408b0fcd790b) | 86  | 80  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/4279b0329e1ea590c2dfde74f697b9f887152e0e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f18d3559-6030-45e6-b389-6db0df0bcbf0) | 50  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.4d915205-575c-4fc2-8586-666972ad5f9a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-11-08 15:20 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/b7a70f683e28ac3c1f86e6c61ecd166b38dcd637/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8cf9018d-93b8-4f7a-a5c1-1f5d69729d44) | 50  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/b7a70f683e28ac3c1f86e6c61ecd166b38dcd637/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8bc22741-48a8-4435-927e-d9c012dc6ffb) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/b7a70f683e28ac3c1f86e6c61ecd166b38dcd637/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/887a9ba7-96d5-45ca-8f55-e005cfb2feb2) | 64  | 80  | 71  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.85ffc9bf-ec23-4b8d-be10-d4e03cd13839?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-10 23:46 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/1964e28f0a89d0f606ad36a51047fbef64fb96be/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/064ef248-7a34-42a3-8561-268c37cbfd78) | 50  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/1964e28f0a89d0f606ad36a51047fbef64fb96be/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2e5fb6cd-273a-4358-9e06-affee67ce7d3) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/1964e28f0a89d0f606ad36a51047fbef64fb96be/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ff4bb62f-c9dd-4659-877a-13a9da505f39) | 64  | 80  | 71  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1b1a7402-a065-4037-8207-70ef6b17ebda?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-12 21:07 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/a100a575517eb1cff4020196456eb3fcc6f43bc3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2e01641f-86bb-4c78-a0b8-7fcb9cf5f01c) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/a100a575517eb1cff4020196456eb3fcc6f43bc3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/47a2c653-f0ad-4cbf-8581-05470932e0b1) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/a100a575517eb1cff4020196456eb3fcc6f43bc3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/51ef7878-ba9c-4d31-9a40-64a0b4e3c596) | 64  | 80  | 71  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b20eb822-8cca-48bc-b7c4-627d5154fe53?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 14:43 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/9c029faac01d4dacb1b012d406be1d010378958e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e1d540e6-bb70-4a06-b67b-d1b4b1fb967a) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/9c029faac01d4dacb1b012d406be1d010378958e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fe7a1e84-9566-42bf-88d9-f89c27f06424) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/9c029faac01d4dacb1b012d406be1d010378958e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/febb5867-393d-4f83-af03-4ffe68e8ab7e) | 65  | 76  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5d97b8bd-4d98-4fe8-b9e5-235d3fa82583?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 15:13 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/97b6d1c1df79b3811b038df39338337b7f24c04b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/776bcf44-30f6-4a43-a59e-a52272289cb9) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/97b6d1c1df79b3811b038df39338337b7f24c04b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/89386d78-528b-4c40-a446-0dbc8eb8ce91) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/97b6d1c1df79b3811b038df39338337b7f24c04b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a532df3d-2329-4cfc-96eb-df25e43ad82e) | 65  | 76  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.941e3a53-00cc-4370-9788-aafe734b52e9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 15:26 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/6f7ec3cf1955128ee598d577b0322647572b85ab/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/feae45c4-b9bb-4c3a-a967-3a3473ac7fe7) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/6f7ec3cf1955128ee598d577b0322647572b85ab/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5b14d989-46d5-4b0e-b7ff-3d198d1da06a) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/6f7ec3cf1955128ee598d577b0322647572b85ab/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/db39de4b-2706-4cbe-abab-06fc98daa8a3) | 60  | 73  | 87  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7d57e3f3-7662-406c-a302-9878461b633d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 18:08 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/943a1b0b4f487764ef933196f2abbe20a62e0b31/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2802eb02-cb92-49e1-9f19-91fd2303be1e) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/943a1b0b4f487764ef933196f2abbe20a62e0b31/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5ebf2476-9b86-4d36-96a8-41186a85ede7) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/943a1b0b4f487764ef933196f2abbe20a62e0b31/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b0aace5b-8aca-462f-8526-a8ebb6a7d387) | 61  | 67  | 88  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5979870f-43c7-425d-a782-66259be21172?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 18:18 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/04b154bb2ad8d85b900c13793503422238f4f3a7/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6993b8ef-c0f3-468a-8264-0db126ff2a4e) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/04b154bb2ad8d85b900c13793503422238f4f3a7/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/81ce0417-bfe0-470c-b1e9-f8da5f9a21ec) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/04b154bb2ad8d85b900c13793503422238f4f3a7/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ea78881d-125d-4a10-bc21-c95f73bc747e) | 64  | 70  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b1d6533c-2803-4e6b-a8b3-4853c9477fc3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 18:52 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/f95544a256907396607610446ca6c77241af0ecf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d03685a0-4e40-4531-bb3d-2d9019fe2b1c) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/f95544a256907396607610446ca6c77241af0ecf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/66d890a8-533d-4d58-986b-343fac09bc85) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/f95544a256907396607610446ca6c77241af0ecf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c18e1655-1f93-4464-a173-ecd82be0f0b3) | 64  | 70  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.411b7438-784d-41f1-b780-666ff8b79b53?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 19:24 UTC, justinabrokwah-okta commented on packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md
> +You can customize the post-authentication prompt text, including the following:
If it makes sense, we can specify that these customizations are per brand as well (already implied by brandId in the URL though)

2024-12-18 19:26 UTC, justinabrokwah-okta commented on packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md
> +You can reset KMSI for an individual user and clear all of their sessions.
nit: We can also mention the end-user settings method to clear all sessions here as well?

2024-12-18 20:24 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/de1613542ca1350880793723c9d5048687867842/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fdfcac2f-1311-46a6-a00e-9bfbfb042b5d) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/de1613542ca1350880793723c9d5048687867842/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/492c761d-f4d2-43fb-8836-97d45cfd1d16) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/de1613542ca1350880793723c9d5048687867842/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/26344e53-2313-4a06-b40e-551ede01bf4d) | 65  | 71  | 94  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.60def1d5-78a3-4545-9534-c243eedd9eb4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 20:38 UTC, grahamsmith-okta requested changes
one mighty small change

2024-12-18 20:38 UTC, grahamsmith-okta commented on packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md
> +In either case, users who select **Keep me signed** in are remembered on their device for the duration set in your authentication policy.
```suggestion
In either case, users who select **Keep me signed in** are remembered on their device for the duration set in your authentication policy.
```

2024-12-18 20:53 UTC, acrolinxdevdocs-okta commented
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/4ec937c87aee3493bf76521f79d14b2a5a61c7c8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/542f7fe6-80b3-47da-a15f-3cb5ca53334a) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/index.md](https://github.com/okta/okta-developer-docs/blob/4ec937c87aee3493bf76521f79d14b2a5a61c7c8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c62c04e-ec70-4a4d-986d-431ce67cabf9) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md](https://github.com/okta/okta-developer-docs/blob/4ec937c87aee3493bf76521f79d14b2a5a61c7c8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fkeep-me-signed-in%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/37de7bf0-258c-431b-9f2c-ed39ef11b8e8) | 65  | 71  | 94  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.20d1a011-8381-4707-b77e-6559fddf5358?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

2024-12-18 20:54 UTC, grahamsmith-okta approved these changes

2024-12-18 20:55 UTC, justinabrokwah-okta approved these changes

2024-12-18 21:04 UTC, merged